/* soapH.h
   Generated by gSOAP 2.8.15 from ctcc_sms_notification_service_2_1.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifdef __cplusplus
extern "C" {
#endif
#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultcode(struct soap *soap);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_serialize_byte(soap, data), soap_begin_send(soap) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_serialize_int(soap, data), soap_begin_send(soap) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns4__TimeMetrics
#define SOAP_TYPE_ns4__TimeMetrics (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns4__TimeMetrics(struct soap*, enum ns4__TimeMetrics *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns4__TimeMetrics(struct soap*, const char*, int, const enum ns4__TimeMetrics *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_ns4__TimeMetrics2s(struct soap*, enum ns4__TimeMetrics);
SOAP_FMAC3 enum ns4__TimeMetrics * SOAP_FMAC4 soap_in_ns4__TimeMetrics(struct soap*, const char*, enum ns4__TimeMetrics *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2ns4__TimeMetrics(struct soap*, const char*, enum ns4__TimeMetrics *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns4__TimeMetrics(struct soap*, const enum ns4__TimeMetrics *, const char*, const char*);

#ifndef soap_write_ns4__TimeMetrics
#define soap_write_ns4__TimeMetrics(soap, data) ( soap_serialize_ns4__TimeMetrics(soap, data), soap_begin_send(soap) || soap_put_ns4__TimeMetrics(soap, data, "ns4:TimeMetrics", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 enum ns4__TimeMetrics * SOAP_FMAC4 soap_get_ns4__TimeMetrics(struct soap*, enum ns4__TimeMetrics *, const char*, const char*);

#ifndef soap_read_ns4__TimeMetrics
#define soap_read_ns4__TimeMetrics(soap, data) ( soap_begin_recv(soap) || !soap_get_ns4__TimeMetrics(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns4__EndReason
#define SOAP_TYPE_ns4__EndReason (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns4__EndReason(struct soap*, enum ns4__EndReason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns4__EndReason(struct soap*, const char*, int, const enum ns4__EndReason *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_ns4__EndReason2s(struct soap*, enum ns4__EndReason);
SOAP_FMAC3 enum ns4__EndReason * SOAP_FMAC4 soap_in_ns4__EndReason(struct soap*, const char*, enum ns4__EndReason *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2ns4__EndReason(struct soap*, const char*, enum ns4__EndReason *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns4__EndReason(struct soap*, const enum ns4__EndReason *, const char*, const char*);

#ifndef soap_write_ns4__EndReason
#define soap_write_ns4__EndReason(soap, data) ( soap_serialize_ns4__EndReason(soap, data), soap_begin_send(soap) || soap_put_ns4__EndReason(soap, data, "ns4:EndReason", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 enum ns4__EndReason * SOAP_FMAC4 soap_get_ns4__EndReason(struct soap*, enum ns4__EndReason *, const char*, const char*);

#ifndef soap_read_ns4__EndReason
#define soap_read_ns4__EndReason(soap, data) ( soap_begin_recv(soap) || !soap_get_ns4__EndReason(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns4__DeliveryConfirmStatus
#define SOAP_TYPE_ns4__DeliveryConfirmStatus (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns4__DeliveryConfirmStatus(struct soap*, enum ns4__DeliveryConfirmStatus *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns4__DeliveryConfirmStatus(struct soap*, const char*, int, const enum ns4__DeliveryConfirmStatus *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_ns4__DeliveryConfirmStatus2s(struct soap*, enum ns4__DeliveryConfirmStatus);
SOAP_FMAC3 enum ns4__DeliveryConfirmStatus * SOAP_FMAC4 soap_in_ns4__DeliveryConfirmStatus(struct soap*, const char*, enum ns4__DeliveryConfirmStatus *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2ns4__DeliveryConfirmStatus(struct soap*, const char*, enum ns4__DeliveryConfirmStatus *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns4__DeliveryConfirmStatus(struct soap*, const enum ns4__DeliveryConfirmStatus *, const char*, const char*);

#ifndef soap_write_ns4__DeliveryConfirmStatus
#define soap_write_ns4__DeliveryConfirmStatus(soap, data) ( soap_serialize_ns4__DeliveryConfirmStatus(soap, data), soap_begin_send(soap) || soap_put_ns4__DeliveryConfirmStatus(soap, data, "ns4:DeliveryConfirmStatus", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 enum ns4__DeliveryConfirmStatus * SOAP_FMAC4 soap_get_ns4__DeliveryConfirmStatus(struct soap*, enum ns4__DeliveryConfirmStatus *, const char*, const char*);

#ifndef soap_read_ns4__DeliveryConfirmStatus
#define soap_read_ns4__DeliveryConfirmStatus(soap, data) ( soap_begin_recv(soap) || !soap_get_ns4__DeliveryConfirmStatus(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns3__SmsFormat
#define SOAP_TYPE_ns3__SmsFormat (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns3__SmsFormat(struct soap*, enum ns3__SmsFormat *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__SmsFormat(struct soap*, const char*, int, const enum ns3__SmsFormat *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_ns3__SmsFormat2s(struct soap*, enum ns3__SmsFormat);
SOAP_FMAC3 enum ns3__SmsFormat * SOAP_FMAC4 soap_in_ns3__SmsFormat(struct soap*, const char*, enum ns3__SmsFormat *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2ns3__SmsFormat(struct soap*, const char*, enum ns3__SmsFormat *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns3__SmsFormat(struct soap*, const enum ns3__SmsFormat *, const char*, const char*);

#ifndef soap_write_ns3__SmsFormat
#define soap_write_ns3__SmsFormat(soap, data) ( soap_serialize_ns3__SmsFormat(soap, data), soap_begin_send(soap) || soap_put_ns3__SmsFormat(soap, data, "ns3:SmsFormat", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 enum ns3__SmsFormat * SOAP_FMAC4 soap_get_ns3__SmsFormat(struct soap*, enum ns3__SmsFormat *, const char*, const char*);

#ifndef soap_read_ns3__SmsFormat
#define soap_read_ns3__SmsFormat(soap, data) ( soap_begin_recv(soap) || !soap_get_ns3__SmsFormat(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns3__DeliveryStatus
#define SOAP_TYPE_ns3__DeliveryStatus (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns3__DeliveryStatus(struct soap*, enum ns3__DeliveryStatus *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__DeliveryStatus(struct soap*, const char*, int, const enum ns3__DeliveryStatus *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_ns3__DeliveryStatus2s(struct soap*, enum ns3__DeliveryStatus);
SOAP_FMAC3 enum ns3__DeliveryStatus * SOAP_FMAC4 soap_in_ns3__DeliveryStatus(struct soap*, const char*, enum ns3__DeliveryStatus *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2ns3__DeliveryStatus(struct soap*, const char*, enum ns3__DeliveryStatus *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns3__DeliveryStatus(struct soap*, const enum ns3__DeliveryStatus *, const char*, const char*);

#ifndef soap_write_ns3__DeliveryStatus
#define soap_write_ns3__DeliveryStatus(soap, data) ( soap_serialize_ns3__DeliveryStatus(soap, data), soap_begin_send(soap) || soap_put_ns3__DeliveryStatus(soap, data, "ns3:DeliveryStatus", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 enum ns3__DeliveryStatus * SOAP_FMAC4 soap_get_ns3__DeliveryStatus(struct soap*, enum ns3__DeliveryStatus *, const char*, const char*);

#ifndef soap_read_ns3__DeliveryStatus
#define soap_read_ns3__DeliveryStatus(soap, data) ( soap_begin_recv(soap) || !soap_get_ns3__DeliveryStatus(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__boolean(struct soap*, enum xsd__boolean *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__boolean(struct soap*, const char*, int, const enum xsd__boolean *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_xsd__boolean2s(struct soap*, enum xsd__boolean);
SOAP_FMAC3 enum xsd__boolean * SOAP_FMAC4 soap_in_xsd__boolean(struct soap*, const char*, enum xsd__boolean *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2xsd__boolean(struct soap*, const char*, enum xsd__boolean *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__boolean(struct soap*, const enum xsd__boolean *, const char*, const char*);

#ifndef soap_write_xsd__boolean
#define soap_write_xsd__boolean(soap, data) ( soap_serialize_xsd__boolean(soap, data), soap_begin_send(soap) || soap_put_xsd__boolean(soap, data, "xsd:boolean", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 enum xsd__boolean * SOAP_FMAC4 soap_get_xsd__boolean(struct soap*, enum xsd__boolean *, const char*, const char*);

#ifndef soap_read_xsd__boolean
#define soap_read_xsd__boolean(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__boolean(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_serialize_SOAP_ENV__Fault(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_serialize_SOAP_ENV__Reason(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_serialize_SOAP_ENV__Detail(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_serialize_SOAP_ENV__Code(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef SOAP_TYPE___ns1__notifySmsDeliveryReceipt
#define SOAP_TYPE___ns1__notifySmsDeliveryReceipt (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__notifySmsDeliveryReceipt(struct soap*, struct __ns1__notifySmsDeliveryReceipt *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__notifySmsDeliveryReceipt(struct soap*, const struct __ns1__notifySmsDeliveryReceipt *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__notifySmsDeliveryReceipt(struct soap*, const char*, int, const struct __ns1__notifySmsDeliveryReceipt *, const char*);
SOAP_FMAC3 struct __ns1__notifySmsDeliveryReceipt * SOAP_FMAC4 soap_in___ns1__notifySmsDeliveryReceipt(struct soap*, const char*, struct __ns1__notifySmsDeliveryReceipt *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__notifySmsDeliveryReceipt(struct soap*, const struct __ns1__notifySmsDeliveryReceipt *, const char*, const char*);

#ifndef soap_write___ns1__notifySmsDeliveryReceipt
#define soap_write___ns1__notifySmsDeliveryReceipt(soap, data) ( soap_serialize___ns1__notifySmsDeliveryReceipt(soap, data), soap_begin_send(soap) || soap_put___ns1__notifySmsDeliveryReceipt(soap, data, "-ns1:notifySmsDeliveryReceipt", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct __ns1__notifySmsDeliveryReceipt * SOAP_FMAC4 soap_get___ns1__notifySmsDeliveryReceipt(struct soap*, struct __ns1__notifySmsDeliveryReceipt *, const char*, const char*);

#ifndef soap_read___ns1__notifySmsDeliveryReceipt
#define soap_read___ns1__notifySmsDeliveryReceipt(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__notifySmsDeliveryReceipt(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE___ns1__notifySmsReception
#define SOAP_TYPE___ns1__notifySmsReception (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__notifySmsReception(struct soap*, struct __ns1__notifySmsReception *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__notifySmsReception(struct soap*, const struct __ns1__notifySmsReception *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__notifySmsReception(struct soap*, const char*, int, const struct __ns1__notifySmsReception *, const char*);
SOAP_FMAC3 struct __ns1__notifySmsReception * SOAP_FMAC4 soap_in___ns1__notifySmsReception(struct soap*, const char*, struct __ns1__notifySmsReception *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__notifySmsReception(struct soap*, const struct __ns1__notifySmsReception *, const char*, const char*);

#ifndef soap_write___ns1__notifySmsReception
#define soap_write___ns1__notifySmsReception(soap, data) ( soap_serialize___ns1__notifySmsReception(soap, data), soap_begin_send(soap) || soap_put___ns1__notifySmsReception(soap, data, "-ns1:notifySmsReception", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct __ns1__notifySmsReception * SOAP_FMAC4 soap_get___ns1__notifySmsReception(struct soap*, struct __ns1__notifySmsReception *, const char*, const char*);

#ifndef soap_read___ns1__notifySmsReception
#define soap_read___ns1__notifySmsReception(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__notifySmsReception(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_serialize_SOAP_ENV__Header(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef SOAP_TYPE_ns4__PolicyException
#define SOAP_TYPE_ns4__PolicyException (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns4__PolicyException(struct soap*, struct ns4__PolicyException *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns4__PolicyException(struct soap*, const struct ns4__PolicyException *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns4__PolicyException(struct soap*, const char*, int, const struct ns4__PolicyException *, const char*);
SOAP_FMAC3 struct ns4__PolicyException * SOAP_FMAC4 soap_in_ns4__PolicyException(struct soap*, const char*, struct ns4__PolicyException *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns4__PolicyException(struct soap*, const struct ns4__PolicyException *, const char*, const char*);

#ifndef soap_write_ns4__PolicyException
#define soap_write_ns4__PolicyException(soap, data) ( soap_serialize_ns4__PolicyException(soap, data), soap_begin_send(soap) || soap_put_ns4__PolicyException(soap, data, "ns4:PolicyException", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns4__PolicyException * SOAP_FMAC4 soap_get_ns4__PolicyException(struct soap*, struct ns4__PolicyException *, const char*, const char*);

#ifndef soap_read_ns4__PolicyException
#define soap_read_ns4__PolicyException(soap, data) ( soap_begin_recv(soap) || !soap_get_ns4__PolicyException(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns4__ServiceException
#define SOAP_TYPE_ns4__ServiceException (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns4__ServiceException(struct soap*, struct ns4__ServiceException *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns4__ServiceException(struct soap*, const struct ns4__ServiceException *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns4__ServiceException(struct soap*, const char*, int, const struct ns4__ServiceException *, const char*);
SOAP_FMAC3 struct ns4__ServiceException * SOAP_FMAC4 soap_in_ns4__ServiceException(struct soap*, const char*, struct ns4__ServiceException *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns4__ServiceException(struct soap*, const struct ns4__ServiceException *, const char*, const char*);

#ifndef soap_write_ns4__ServiceException
#define soap_write_ns4__ServiceException(soap, data) ( soap_serialize_ns4__ServiceException(soap, data), soap_begin_send(soap) || soap_put_ns4__ServiceException(soap, data, "ns4:ServiceException", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns4__ServiceException * SOAP_FMAC4 soap_get_ns4__ServiceException(struct soap*, struct ns4__ServiceException *, const char*, const char*);

#ifndef soap_read_ns4__ServiceException
#define soap_read_ns4__ServiceException(soap, data) ( soap_begin_recv(soap) || !soap_get_ns4__ServiceException(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns4__ServiceError
#define SOAP_TYPE_ns4__ServiceError (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns4__ServiceError(struct soap*, struct ns4__ServiceError *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns4__ServiceError(struct soap*, const struct ns4__ServiceError *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns4__ServiceError(struct soap*, const char*, int, const struct ns4__ServiceError *, const char*);
SOAP_FMAC3 struct ns4__ServiceError * SOAP_FMAC4 soap_in_ns4__ServiceError(struct soap*, const char*, struct ns4__ServiceError *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns4__ServiceError(struct soap*, const struct ns4__ServiceError *, const char*, const char*);

#ifndef soap_write_ns4__ServiceError
#define soap_write_ns4__ServiceError(soap, data) ( soap_serialize_ns4__ServiceError(soap, data), soap_begin_send(soap) || soap_put_ns4__ServiceError(soap, data, "ns4:ServiceError", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns4__ServiceError * SOAP_FMAC4 soap_get_ns4__ServiceError(struct soap*, struct ns4__ServiceError *, const char*, const char*);

#ifndef soap_read_ns4__ServiceError
#define soap_read_ns4__ServiceError(soap, data) ( soap_begin_recv(soap) || !soap_get_ns4__ServiceError(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns4__SimpleReference
#define SOAP_TYPE_ns4__SimpleReference (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns4__SimpleReference(struct soap*, struct ns4__SimpleReference *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns4__SimpleReference(struct soap*, const struct ns4__SimpleReference *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns4__SimpleReference(struct soap*, const char*, int, const struct ns4__SimpleReference *, const char*);
SOAP_FMAC3 struct ns4__SimpleReference * SOAP_FMAC4 soap_in_ns4__SimpleReference(struct soap*, const char*, struct ns4__SimpleReference *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns4__SimpleReference(struct soap*, const struct ns4__SimpleReference *, const char*, const char*);

#ifndef soap_write_ns4__SimpleReference
#define soap_write_ns4__SimpleReference(soap, data) ( soap_serialize_ns4__SimpleReference(soap, data), soap_begin_send(soap) || soap_put_ns4__SimpleReference(soap, data, "ns4:SimpleReference", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns4__SimpleReference * SOAP_FMAC4 soap_get_ns4__SimpleReference(struct soap*, struct ns4__SimpleReference *, const char*, const char*);

#ifndef soap_read_ns4__SimpleReference
#define soap_read_ns4__SimpleReference(soap, data) ( soap_begin_recv(soap) || !soap_get_ns4__SimpleReference(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns4__ChargingInformation
#define SOAP_TYPE_ns4__ChargingInformation (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns4__ChargingInformation(struct soap*, struct ns4__ChargingInformation *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns4__ChargingInformation(struct soap*, const struct ns4__ChargingInformation *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns4__ChargingInformation(struct soap*, const char*, int, const struct ns4__ChargingInformation *, const char*);
SOAP_FMAC3 struct ns4__ChargingInformation * SOAP_FMAC4 soap_in_ns4__ChargingInformation(struct soap*, const char*, struct ns4__ChargingInformation *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns4__ChargingInformation(struct soap*, const struct ns4__ChargingInformation *, const char*, const char*);

#ifndef soap_write_ns4__ChargingInformation
#define soap_write_ns4__ChargingInformation(soap, data) ( soap_serialize_ns4__ChargingInformation(soap, data), soap_begin_send(soap) || soap_put_ns4__ChargingInformation(soap, data, "ns4:ChargingInformation", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns4__ChargingInformation * SOAP_FMAC4 soap_get_ns4__ChargingInformation(struct soap*, struct ns4__ChargingInformation *, const char*, const char*);

#ifndef soap_read_ns4__ChargingInformation
#define soap_read_ns4__ChargingInformation(soap, data) ( soap_begin_recv(soap) || !soap_get_ns4__ChargingInformation(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns4__TimeMetric
#define SOAP_TYPE_ns4__TimeMetric (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns4__TimeMetric(struct soap*, struct ns4__TimeMetric *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns4__TimeMetric(struct soap*, const struct ns4__TimeMetric *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns4__TimeMetric(struct soap*, const char*, int, const struct ns4__TimeMetric *, const char*);
SOAP_FMAC3 struct ns4__TimeMetric * SOAP_FMAC4 soap_in_ns4__TimeMetric(struct soap*, const char*, struct ns4__TimeMetric *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns4__TimeMetric(struct soap*, const struct ns4__TimeMetric *, const char*, const char*);

#ifndef soap_write_ns4__TimeMetric
#define soap_write_ns4__TimeMetric(soap, data) ( soap_serialize_ns4__TimeMetric(soap, data), soap_begin_send(soap) || soap_put_ns4__TimeMetric(soap, data, "ns4:TimeMetric", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns4__TimeMetric * SOAP_FMAC4 soap_get_ns4__TimeMetric(struct soap*, struct ns4__TimeMetric *, const char*, const char*);

#ifndef soap_read_ns4__TimeMetric
#define soap_read_ns4__TimeMetric(soap, data) ( soap_begin_recv(soap) || !soap_get_ns4__TimeMetric(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns4__NotifySOAPHeader
#define SOAP_TYPE_ns4__NotifySOAPHeader (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns4__NotifySOAPHeader(struct soap*, struct ns4__NotifySOAPHeader *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns4__NotifySOAPHeader(struct soap*, const struct ns4__NotifySOAPHeader *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns4__NotifySOAPHeader(struct soap*, const char*, int, const struct ns4__NotifySOAPHeader *, const char*);
SOAP_FMAC3 struct ns4__NotifySOAPHeader * SOAP_FMAC4 soap_in_ns4__NotifySOAPHeader(struct soap*, const char*, struct ns4__NotifySOAPHeader *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns4__NotifySOAPHeader(struct soap*, const struct ns4__NotifySOAPHeader *, const char*, const char*);

#ifndef soap_write_ns4__NotifySOAPHeader
#define soap_write_ns4__NotifySOAPHeader(soap, data) ( soap_serialize_ns4__NotifySOAPHeader(soap, data), soap_begin_send(soap) || soap_put_ns4__NotifySOAPHeader(soap, data, "ns4:NotifySOAPHeader", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns4__NotifySOAPHeader * SOAP_FMAC4 soap_get_ns4__NotifySOAPHeader(struct soap*, struct ns4__NotifySOAPHeader *, const char*, const char*);

#ifndef soap_read_ns4__NotifySOAPHeader
#define soap_read_ns4__NotifySOAPHeader(soap, data) ( soap_begin_recv(soap) || !soap_get_ns4__NotifySOAPHeader(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns4__RequestSOAPHeader
#define SOAP_TYPE_ns4__RequestSOAPHeader (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns4__RequestSOAPHeader(struct soap*, struct ns4__RequestSOAPHeader *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns4__RequestSOAPHeader(struct soap*, const struct ns4__RequestSOAPHeader *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns4__RequestSOAPHeader(struct soap*, const char*, int, const struct ns4__RequestSOAPHeader *, const char*);
SOAP_FMAC3 struct ns4__RequestSOAPHeader * SOAP_FMAC4 soap_in_ns4__RequestSOAPHeader(struct soap*, const char*, struct ns4__RequestSOAPHeader *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns4__RequestSOAPHeader(struct soap*, const struct ns4__RequestSOAPHeader *, const char*, const char*);

#ifndef soap_write_ns4__RequestSOAPHeader
#define soap_write_ns4__RequestSOAPHeader(soap, data) ( soap_serialize_ns4__RequestSOAPHeader(soap, data), soap_begin_send(soap) || soap_put_ns4__RequestSOAPHeader(soap, data, "ns4:RequestSOAPHeader", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns4__RequestSOAPHeader * SOAP_FMAC4 soap_get_ns4__RequestSOAPHeader(struct soap*, struct ns4__RequestSOAPHeader *, const char*, const char*);

#ifndef soap_read_ns4__RequestSOAPHeader
#define soap_read_ns4__RequestSOAPHeader(soap, data) ( soap_begin_recv(soap) || !soap_get_ns4__RequestSOAPHeader(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns2__notifySmsDeliveryReceiptResponse
#define SOAP_TYPE_ns2__notifySmsDeliveryReceiptResponse (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__notifySmsDeliveryReceiptResponse(struct soap*, struct ns2__notifySmsDeliveryReceiptResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__notifySmsDeliveryReceiptResponse(struct soap*, const struct ns2__notifySmsDeliveryReceiptResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__notifySmsDeliveryReceiptResponse(struct soap*, const char*, int, const struct ns2__notifySmsDeliveryReceiptResponse *, const char*);
SOAP_FMAC3 struct ns2__notifySmsDeliveryReceiptResponse * SOAP_FMAC4 soap_in_ns2__notifySmsDeliveryReceiptResponse(struct soap*, const char*, struct ns2__notifySmsDeliveryReceiptResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__notifySmsDeliveryReceiptResponse(struct soap*, const struct ns2__notifySmsDeliveryReceiptResponse *, const char*, const char*);

#ifndef soap_write_ns2__notifySmsDeliveryReceiptResponse
#define soap_write_ns2__notifySmsDeliveryReceiptResponse(soap, data) ( soap_serialize_ns2__notifySmsDeliveryReceiptResponse(soap, data), soap_begin_send(soap) || soap_put_ns2__notifySmsDeliveryReceiptResponse(soap, data, "ns2:notifySmsDeliveryReceiptResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__notifySmsDeliveryReceiptResponse * SOAP_FMAC4 soap_get_ns2__notifySmsDeliveryReceiptResponse(struct soap*, struct ns2__notifySmsDeliveryReceiptResponse *, const char*, const char*);

#ifndef soap_read_ns2__notifySmsDeliveryReceiptResponse
#define soap_read_ns2__notifySmsDeliveryReceiptResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__notifySmsDeliveryReceiptResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns3__DeliveryInformation
#define SOAP_TYPE_ns3__DeliveryInformation (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns3__DeliveryInformation(struct soap*, struct ns3__DeliveryInformation *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns3__DeliveryInformation(struct soap*, const struct ns3__DeliveryInformation *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__DeliveryInformation(struct soap*, const char*, int, const struct ns3__DeliveryInformation *, const char*);
SOAP_FMAC3 struct ns3__DeliveryInformation * SOAP_FMAC4 soap_in_ns3__DeliveryInformation(struct soap*, const char*, struct ns3__DeliveryInformation *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns3__DeliveryInformation(struct soap*, const struct ns3__DeliveryInformation *, const char*, const char*);

#ifndef soap_write_ns3__DeliveryInformation
#define soap_write_ns3__DeliveryInformation(soap, data) ( soap_serialize_ns3__DeliveryInformation(soap, data), soap_begin_send(soap) || soap_put_ns3__DeliveryInformation(soap, data, "ns3:DeliveryInformation", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns3__DeliveryInformation * SOAP_FMAC4 soap_get_ns3__DeliveryInformation(struct soap*, struct ns3__DeliveryInformation *, const char*, const char*);

#ifndef soap_read_ns3__DeliveryInformation
#define soap_read_ns3__DeliveryInformation(soap, data) ( soap_begin_recv(soap) || !soap_get_ns3__DeliveryInformation(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns2__notifySmsDeliveryReceipt
#define SOAP_TYPE_ns2__notifySmsDeliveryReceipt (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__notifySmsDeliveryReceipt(struct soap*, struct ns2__notifySmsDeliveryReceipt *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__notifySmsDeliveryReceipt(struct soap*, const struct ns2__notifySmsDeliveryReceipt *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__notifySmsDeliveryReceipt(struct soap*, const char*, int, const struct ns2__notifySmsDeliveryReceipt *, const char*);
SOAP_FMAC3 struct ns2__notifySmsDeliveryReceipt * SOAP_FMAC4 soap_in_ns2__notifySmsDeliveryReceipt(struct soap*, const char*, struct ns2__notifySmsDeliveryReceipt *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__notifySmsDeliveryReceipt(struct soap*, const struct ns2__notifySmsDeliveryReceipt *, const char*, const char*);

#ifndef soap_write_ns2__notifySmsDeliveryReceipt
#define soap_write_ns2__notifySmsDeliveryReceipt(soap, data) ( soap_serialize_ns2__notifySmsDeliveryReceipt(soap, data), soap_begin_send(soap) || soap_put_ns2__notifySmsDeliveryReceipt(soap, data, "ns2:notifySmsDeliveryReceipt", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__notifySmsDeliveryReceipt * SOAP_FMAC4 soap_get_ns2__notifySmsDeliveryReceipt(struct soap*, struct ns2__notifySmsDeliveryReceipt *, const char*, const char*);

#ifndef soap_read_ns2__notifySmsDeliveryReceipt
#define soap_read_ns2__notifySmsDeliveryReceipt(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__notifySmsDeliveryReceipt(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns2__notifySmsReceptionResponse
#define SOAP_TYPE_ns2__notifySmsReceptionResponse (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__notifySmsReceptionResponse(struct soap*, struct ns2__notifySmsReceptionResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__notifySmsReceptionResponse(struct soap*, const struct ns2__notifySmsReceptionResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__notifySmsReceptionResponse(struct soap*, const char*, int, const struct ns2__notifySmsReceptionResponse *, const char*);
SOAP_FMAC3 struct ns2__notifySmsReceptionResponse * SOAP_FMAC4 soap_in_ns2__notifySmsReceptionResponse(struct soap*, const char*, struct ns2__notifySmsReceptionResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__notifySmsReceptionResponse(struct soap*, const struct ns2__notifySmsReceptionResponse *, const char*, const char*);

#ifndef soap_write_ns2__notifySmsReceptionResponse
#define soap_write_ns2__notifySmsReceptionResponse(soap, data) ( soap_serialize_ns2__notifySmsReceptionResponse(soap, data), soap_begin_send(soap) || soap_put_ns2__notifySmsReceptionResponse(soap, data, "ns2:notifySmsReceptionResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__notifySmsReceptionResponse * SOAP_FMAC4 soap_get_ns2__notifySmsReceptionResponse(struct soap*, struct ns2__notifySmsReceptionResponse *, const char*, const char*);

#ifndef soap_read_ns2__notifySmsReceptionResponse
#define soap_read_ns2__notifySmsReceptionResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__notifySmsReceptionResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns3__SmsMessage
#define SOAP_TYPE_ns3__SmsMessage (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns3__SmsMessage(struct soap*, struct ns3__SmsMessage *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns3__SmsMessage(struct soap*, const struct ns3__SmsMessage *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__SmsMessage(struct soap*, const char*, int, const struct ns3__SmsMessage *, const char*);
SOAP_FMAC3 struct ns3__SmsMessage * SOAP_FMAC4 soap_in_ns3__SmsMessage(struct soap*, const char*, struct ns3__SmsMessage *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns3__SmsMessage(struct soap*, const struct ns3__SmsMessage *, const char*, const char*);

#ifndef soap_write_ns3__SmsMessage
#define soap_write_ns3__SmsMessage(soap, data) ( soap_serialize_ns3__SmsMessage(soap, data), soap_begin_send(soap) || soap_put_ns3__SmsMessage(soap, data, "ns3:SmsMessage", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns3__SmsMessage * SOAP_FMAC4 soap_get_ns3__SmsMessage(struct soap*, struct ns3__SmsMessage *, const char*, const char*);

#ifndef soap_read_ns3__SmsMessage
#define soap_read_ns3__SmsMessage(soap, data) ( soap_begin_recv(soap) || !soap_get_ns3__SmsMessage(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns2__notifySmsReception
#define SOAP_TYPE_ns2__notifySmsReception (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__notifySmsReception(struct soap*, struct ns2__notifySmsReception *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__notifySmsReception(struct soap*, const struct ns2__notifySmsReception *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__notifySmsReception(struct soap*, const char*, int, const struct ns2__notifySmsReception *, const char*);
SOAP_FMAC3 struct ns2__notifySmsReception * SOAP_FMAC4 soap_in_ns2__notifySmsReception(struct soap*, const char*, struct ns2__notifySmsReception *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__notifySmsReception(struct soap*, const struct ns2__notifySmsReception *, const char*, const char*);

#ifndef soap_write_ns2__notifySmsReception
#define soap_write_ns2__notifySmsReception(soap, data) ( soap_serialize_ns2__notifySmsReception(soap, data), soap_begin_send(soap) || soap_put_ns2__notifySmsReception(soap, data, "ns2:notifySmsReception", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__notifySmsReception * SOAP_FMAC4 soap_get_ns2__notifySmsReception(struct soap*, struct ns2__notifySmsReception *, const char*, const char*);

#ifndef soap_read_ns2__notifySmsReception
#define soap_read_ns2__notifySmsReception(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__notifySmsReception(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_serialize_PointerToSOAP_ENV__Reason(soap, data), soap_begin_send(soap) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_serialize_PointerToSOAP_ENV__Detail(soap, data), soap_begin_send(soap) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_serialize_PointerToSOAP_ENV__Code(soap, data), soap_begin_send(soap) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef SOAP_TYPE_PointerTons2__notifySmsDeliveryReceiptResponse
#define SOAP_TYPE_PointerTons2__notifySmsDeliveryReceiptResponse (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__notifySmsDeliveryReceiptResponse(struct soap*, struct ns2__notifySmsDeliveryReceiptResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__notifySmsDeliveryReceiptResponse(struct soap*, const char *, int, struct ns2__notifySmsDeliveryReceiptResponse *const*, const char *);
SOAP_FMAC3 struct ns2__notifySmsDeliveryReceiptResponse ** SOAP_FMAC4 soap_in_PointerTons2__notifySmsDeliveryReceiptResponse(struct soap*, const char*, struct ns2__notifySmsDeliveryReceiptResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__notifySmsDeliveryReceiptResponse(struct soap*, struct ns2__notifySmsDeliveryReceiptResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__notifySmsDeliveryReceiptResponse
#define soap_write_PointerTons2__notifySmsDeliveryReceiptResponse(soap, data) ( soap_serialize_PointerTons2__notifySmsDeliveryReceiptResponse(soap, data), soap_begin_send(soap) || soap_put_PointerTons2__notifySmsDeliveryReceiptResponse(soap, data, "ns2:notifySmsDeliveryReceiptResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__notifySmsDeliveryReceiptResponse ** SOAP_FMAC4 soap_get_PointerTons2__notifySmsDeliveryReceiptResponse(struct soap*, struct ns2__notifySmsDeliveryReceiptResponse **, const char*, const char*);

#ifndef soap_read_PointerTons2__notifySmsDeliveryReceiptResponse
#define soap_read_PointerTons2__notifySmsDeliveryReceiptResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__notifySmsDeliveryReceiptResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons2__notifySmsDeliveryReceipt
#define SOAP_TYPE_PointerTons2__notifySmsDeliveryReceipt (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__notifySmsDeliveryReceipt(struct soap*, struct ns2__notifySmsDeliveryReceipt *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__notifySmsDeliveryReceipt(struct soap*, const char *, int, struct ns2__notifySmsDeliveryReceipt *const*, const char *);
SOAP_FMAC3 struct ns2__notifySmsDeliveryReceipt ** SOAP_FMAC4 soap_in_PointerTons2__notifySmsDeliveryReceipt(struct soap*, const char*, struct ns2__notifySmsDeliveryReceipt **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__notifySmsDeliveryReceipt(struct soap*, struct ns2__notifySmsDeliveryReceipt *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__notifySmsDeliveryReceipt
#define soap_write_PointerTons2__notifySmsDeliveryReceipt(soap, data) ( soap_serialize_PointerTons2__notifySmsDeliveryReceipt(soap, data), soap_begin_send(soap) || soap_put_PointerTons2__notifySmsDeliveryReceipt(soap, data, "ns2:notifySmsDeliveryReceipt", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__notifySmsDeliveryReceipt ** SOAP_FMAC4 soap_get_PointerTons2__notifySmsDeliveryReceipt(struct soap*, struct ns2__notifySmsDeliveryReceipt **, const char*, const char*);

#ifndef soap_read_PointerTons2__notifySmsDeliveryReceipt
#define soap_read_PointerTons2__notifySmsDeliveryReceipt(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__notifySmsDeliveryReceipt(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons2__notifySmsReceptionResponse
#define SOAP_TYPE_PointerTons2__notifySmsReceptionResponse (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__notifySmsReceptionResponse(struct soap*, struct ns2__notifySmsReceptionResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__notifySmsReceptionResponse(struct soap*, const char *, int, struct ns2__notifySmsReceptionResponse *const*, const char *);
SOAP_FMAC3 struct ns2__notifySmsReceptionResponse ** SOAP_FMAC4 soap_in_PointerTons2__notifySmsReceptionResponse(struct soap*, const char*, struct ns2__notifySmsReceptionResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__notifySmsReceptionResponse(struct soap*, struct ns2__notifySmsReceptionResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__notifySmsReceptionResponse
#define soap_write_PointerTons2__notifySmsReceptionResponse(soap, data) ( soap_serialize_PointerTons2__notifySmsReceptionResponse(soap, data), soap_begin_send(soap) || soap_put_PointerTons2__notifySmsReceptionResponse(soap, data, "ns2:notifySmsReceptionResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__notifySmsReceptionResponse ** SOAP_FMAC4 soap_get_PointerTons2__notifySmsReceptionResponse(struct soap*, struct ns2__notifySmsReceptionResponse **, const char*, const char*);

#ifndef soap_read_PointerTons2__notifySmsReceptionResponse
#define soap_read_PointerTons2__notifySmsReceptionResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__notifySmsReceptionResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons2__notifySmsReception
#define SOAP_TYPE_PointerTons2__notifySmsReception (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__notifySmsReception(struct soap*, struct ns2__notifySmsReception *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__notifySmsReception(struct soap*, const char *, int, struct ns2__notifySmsReception *const*, const char *);
SOAP_FMAC3 struct ns2__notifySmsReception ** SOAP_FMAC4 soap_in_PointerTons2__notifySmsReception(struct soap*, const char*, struct ns2__notifySmsReception **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__notifySmsReception(struct soap*, struct ns2__notifySmsReception *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__notifySmsReception
#define soap_write_PointerTons2__notifySmsReception(soap, data) ( soap_serialize_PointerTons2__notifySmsReception(soap, data), soap_begin_send(soap) || soap_put_PointerTons2__notifySmsReception(soap, data, "ns2:notifySmsReception", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__notifySmsReception ** SOAP_FMAC4 soap_get_PointerTons2__notifySmsReception(struct soap*, struct ns2__notifySmsReception **, const char*, const char*);

#ifndef soap_read_PointerTons2__notifySmsReception
#define soap_read_PointerTons2__notifySmsReception(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__notifySmsReception(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons4__NotifySOAPHeader
#define SOAP_TYPE_PointerTons4__NotifySOAPHeader (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons4__NotifySOAPHeader(struct soap*, struct ns4__NotifySOAPHeader *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons4__NotifySOAPHeader(struct soap*, const char *, int, struct ns4__NotifySOAPHeader *const*, const char *);
SOAP_FMAC3 struct ns4__NotifySOAPHeader ** SOAP_FMAC4 soap_in_PointerTons4__NotifySOAPHeader(struct soap*, const char*, struct ns4__NotifySOAPHeader **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons4__NotifySOAPHeader(struct soap*, struct ns4__NotifySOAPHeader *const*, const char*, const char*);

#ifndef soap_write_PointerTons4__NotifySOAPHeader
#define soap_write_PointerTons4__NotifySOAPHeader(soap, data) ( soap_serialize_PointerTons4__NotifySOAPHeader(soap, data), soap_begin_send(soap) || soap_put_PointerTons4__NotifySOAPHeader(soap, data, "ns4:NotifySOAPHeader", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns4__NotifySOAPHeader ** SOAP_FMAC4 soap_get_PointerTons4__NotifySOAPHeader(struct soap*, struct ns4__NotifySOAPHeader **, const char*, const char*);

#ifndef soap_read_PointerTons4__NotifySOAPHeader
#define soap_read_PointerTons4__NotifySOAPHeader(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons4__NotifySOAPHeader(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTostring
#define SOAP_TYPE_PointerTostring (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostring(struct soap*, char **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostring(struct soap*, const char *, int, char **const*, const char *);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_in_PointerTostring(struct soap*, const char*, char ***, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostring(struct soap*, char **const*, const char*, const char*);

#ifndef soap_write_PointerTostring
#define soap_write_PointerTostring(soap, data) ( soap_serialize_PointerTostring(soap, data), soap_begin_send(soap) || soap_put_PointerTostring(soap, data, "byte", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 char *** SOAP_FMAC4 soap_get_PointerTostring(struct soap*, char ***, const char*, const char*);

#ifndef soap_read_PointerTostring
#define soap_read_PointerTostring(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTostring(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerToxsd__boolean
#define SOAP_TYPE_PointerToxsd__boolean (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToxsd__boolean(struct soap*, enum xsd__boolean *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToxsd__boolean(struct soap*, const char *, int, enum xsd__boolean *const*, const char *);
SOAP_FMAC3 enum xsd__boolean ** SOAP_FMAC4 soap_in_PointerToxsd__boolean(struct soap*, const char*, enum xsd__boolean **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToxsd__boolean(struct soap*, enum xsd__boolean *const*, const char*, const char*);

#ifndef soap_write_PointerToxsd__boolean
#define soap_write_PointerToxsd__boolean(soap, data) ( soap_serialize_PointerToxsd__boolean(soap, data), soap_begin_send(soap) || soap_put_PointerToxsd__boolean(soap, data, "xsd:boolean", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 enum xsd__boolean ** SOAP_FMAC4 soap_get_PointerToxsd__boolean(struct soap*, enum xsd__boolean **, const char*, const char*);

#ifndef soap_read_PointerToxsd__boolean
#define soap_read_PointerToxsd__boolean(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToxsd__boolean(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons4__EndReason
#define SOAP_TYPE_PointerTons4__EndReason (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons4__EndReason(struct soap*, enum ns4__EndReason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons4__EndReason(struct soap*, const char *, int, enum ns4__EndReason *const*, const char *);
SOAP_FMAC3 enum ns4__EndReason ** SOAP_FMAC4 soap_in_PointerTons4__EndReason(struct soap*, const char*, enum ns4__EndReason **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons4__EndReason(struct soap*, enum ns4__EndReason *const*, const char*, const char*);

#ifndef soap_write_PointerTons4__EndReason
#define soap_write_PointerTons4__EndReason(soap, data) ( soap_serialize_PointerTons4__EndReason(soap, data), soap_begin_send(soap) || soap_put_PointerTons4__EndReason(soap, data, "ns4:EndReason", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 enum ns4__EndReason ** SOAP_FMAC4 soap_get_PointerTons4__EndReason(struct soap*, enum ns4__EndReason **, const char*, const char*);

#ifndef soap_read_PointerTons4__EndReason
#define soap_read_PointerTons4__EndReason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons4__EndReason(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons3__DeliveryInformation
#define SOAP_TYPE_PointerTons3__DeliveryInformation (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__DeliveryInformation(struct soap*, struct ns3__DeliveryInformation *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__DeliveryInformation(struct soap*, const char *, int, struct ns3__DeliveryInformation *const*, const char *);
SOAP_FMAC3 struct ns3__DeliveryInformation ** SOAP_FMAC4 soap_in_PointerTons3__DeliveryInformation(struct soap*, const char*, struct ns3__DeliveryInformation **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__DeliveryInformation(struct soap*, struct ns3__DeliveryInformation *const*, const char*, const char*);

#ifndef soap_write_PointerTons3__DeliveryInformation
#define soap_write_PointerTons3__DeliveryInformation(soap, data) ( soap_serialize_PointerTons3__DeliveryInformation(soap, data), soap_begin_send(soap) || soap_put_PointerTons3__DeliveryInformation(soap, data, "ns3:DeliveryInformation", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns3__DeliveryInformation ** SOAP_FMAC4 soap_get_PointerTons3__DeliveryInformation(struct soap*, struct ns3__DeliveryInformation **, const char*, const char*);

#ifndef soap_read_PointerTons3__DeliveryInformation
#define soap_read_PointerTons3__DeliveryInformation(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons3__DeliveryInformation(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons3__SmsMessage
#define SOAP_TYPE_PointerTons3__SmsMessage (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__SmsMessage(struct soap*, struct ns3__SmsMessage *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__SmsMessage(struct soap*, const char *, int, struct ns3__SmsMessage *const*, const char *);
SOAP_FMAC3 struct ns3__SmsMessage ** SOAP_FMAC4 soap_in_PointerTons3__SmsMessage(struct soap*, const char*, struct ns3__SmsMessage **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__SmsMessage(struct soap*, struct ns3__SmsMessage *const*, const char*, const char*);

#ifndef soap_write_PointerTons3__SmsMessage
#define soap_write_PointerTons3__SmsMessage(soap, data) ( soap_serialize_PointerTons3__SmsMessage(soap, data), soap_begin_send(soap) || soap_put_PointerTons3__SmsMessage(soap, data, "ns3:SmsMessage", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns3__SmsMessage ** SOAP_FMAC4 soap_get_PointerTons3__SmsMessage(struct soap*, struct ns3__SmsMessage **, const char*, const char*);

#ifndef soap_read_PointerTons3__SmsMessage
#define soap_read_PointerTons3__SmsMessage(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons3__SmsMessage(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_xsd__decimal
#define SOAP_TYPE_xsd__decimal (9)
#endif

#define soap_default_xsd__decimal(soap, a) soap_default_string(soap, a)

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__decimal(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__decimal(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__decimal(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__decimal(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write_xsd__decimal
#define soap_write_xsd__decimal(soap, data) ( soap_serialize_xsd__decimal(soap, data), soap_begin_send(soap) || soap_put_xsd__decimal(soap, data, "byte", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__decimal(struct soap*, char **, const char*, const char*);

#ifndef soap_read_xsd__decimal
#define soap_read_xsd__decimal(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__decimal(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_xsd__anyURI
#define SOAP_TYPE_xsd__anyURI (8)
#endif

#define soap_default_xsd__anyURI(soap, a) soap_default_string(soap, a)

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__anyURI(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__anyURI(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__anyURI(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__anyURI(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write_xsd__anyURI
#define soap_write_xsd__anyURI(soap, data) ( soap_serialize_xsd__anyURI(soap, data), soap_begin_send(soap) || soap_put_xsd__anyURI(soap, data, "byte", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__anyURI(struct soap*, char **, const char*, const char*);

#ifndef soap_read_xsd__anyURI
#define soap_read_xsd__anyURI(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__anyURI(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_serialize__QName(soap, data), soap_begin_send(soap) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_serialize_string(soap, data), soap_begin_send(soap) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifdef __cplusplus
}
#endif

#endif

/* End of soapH.h */
