/* soapClient.c
   Generated by gSOAP 2.8.15 from SmsNotificationService.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.8.15 2013-10-12 08:52:15 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__notifySmsReception(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__SmsMessage *_in0, struct ns1__notifySmsReceptionResponse *_param_1)
{	struct ns1__notifySmsReception soap_tmp_ns1__notifySmsReception;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8080/services/com/ceno/bss/besttone/nmsccharge/cp/sms/notification/prototype/SmsNotificationService";
	if (soap_action == NULL)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp_ns1__notifySmsReception._in0 = _in0;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__notifySmsReception(soap, &soap_tmp_ns1__notifySmsReception);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__notifySmsReception(soap, &soap_tmp_ns1__notifySmsReception, "ns1:notifySmsReception", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__notifySmsReception(soap, &soap_tmp_ns1__notifySmsReception, "ns1:notifySmsReception", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_1)
		return soap_closesock(soap);
	soap_default_ns1__notifySmsReceptionResponse(soap, _param_1);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__notifySmsReceptionResponse(soap, _param_1, "ns1:notifySmsReceptionResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__notifySmsDeliveryReceipt(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_in0, struct ns1__DeliveryInformation *_in1, struct ns1__notifySmsDeliveryReceiptResponse *_param_2)
{	struct ns1__notifySmsDeliveryReceipt soap_tmp_ns1__notifySmsDeliveryReceipt;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8080/services/com/ceno/bss/besttone/nmsccharge/cp/sms/notification/prototype/SmsNotificationService";
	if (soap_action == NULL)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp_ns1__notifySmsDeliveryReceipt._in0 = _in0;
	soap_tmp_ns1__notifySmsDeliveryReceipt._in1 = _in1;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__notifySmsDeliveryReceipt(soap, &soap_tmp_ns1__notifySmsDeliveryReceipt);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__notifySmsDeliveryReceipt(soap, &soap_tmp_ns1__notifySmsDeliveryReceipt, "ns1:notifySmsDeliveryReceipt", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__notifySmsDeliveryReceipt(soap, &soap_tmp_ns1__notifySmsDeliveryReceipt, "ns1:notifySmsDeliveryReceipt", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_param_2)
		return soap_closesock(soap);
	soap_default_ns1__notifySmsDeliveryReceiptResponse(soap, _param_2);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns1__notifySmsDeliveryReceiptResponse(soap, _param_2, "ns1:notifySmsDeliveryReceiptResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
