/* soapH.h
   Generated by gSOAP 2.8.15 from ctcc_sms_send_service_2_1.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifdef __cplusplus
extern "C" {
#endif
#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultcode(struct soap *soap);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_serialize_byte(soap, data), soap_begin_send(soap) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_serialize_int(soap, data), soap_begin_send(soap) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_unsignedByte
#define SOAP_TYPE_unsignedByte (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedByte(struct soap*, unsigned char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedByte(struct soap*, const char*, int, const unsigned char *, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_in_unsignedByte(struct soap*, const char*, unsigned char *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedByte(struct soap*, const unsigned char *, const char*, const char*);

#ifndef soap_write_unsignedByte
#define soap_write_unsignedByte(soap, data) ( soap_serialize_unsignedByte(soap, data), soap_begin_send(soap) || soap_put_unsignedByte(soap, data, "unsignedByte", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_get_unsignedByte(struct soap*, unsigned char *, const char*, const char*);

#ifndef soap_read_unsignedByte
#define soap_read_unsignedByte(soap, data) ( soap_begin_recv(soap) || !soap_get_unsignedByte(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_unsignedInt
#define SOAP_TYPE_unsignedInt (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedInt(struct soap*, unsigned int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedInt(struct soap*, const char*, int, const unsigned int *, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_in_unsignedInt(struct soap*, const char*, unsigned int *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedInt(struct soap*, const unsigned int *, const char*, const char*);

#ifndef soap_write_unsignedInt
#define soap_write_unsignedInt(soap, data) ( soap_serialize_unsignedInt(soap, data), soap_begin_send(soap) || soap_put_unsignedInt(soap, data, "unsignedInt", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_get_unsignedInt(struct soap*, unsigned int *, const char*, const char*);

#ifndef soap_read_unsignedInt
#define soap_read_unsignedInt(soap, data) ( soap_begin_recv(soap) || !soap_get_unsignedInt(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns5__SmsFormat
#define SOAP_TYPE_ns5__SmsFormat (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns5__SmsFormat(struct soap*, enum ns5__SmsFormat *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns5__SmsFormat(struct soap*, const char*, int, const enum ns5__SmsFormat *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_ns5__SmsFormat2s(struct soap*, enum ns5__SmsFormat);
SOAP_FMAC3 enum ns5__SmsFormat * SOAP_FMAC4 soap_in_ns5__SmsFormat(struct soap*, const char*, enum ns5__SmsFormat *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2ns5__SmsFormat(struct soap*, const char*, enum ns5__SmsFormat *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns5__SmsFormat(struct soap*, const enum ns5__SmsFormat *, const char*, const char*);

#ifndef soap_write_ns5__SmsFormat
#define soap_write_ns5__SmsFormat(soap, data) ( soap_serialize_ns5__SmsFormat(soap, data), soap_begin_send(soap) || soap_put_ns5__SmsFormat(soap, data, "ns5:SmsFormat", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 enum ns5__SmsFormat * SOAP_FMAC4 soap_get_ns5__SmsFormat(struct soap*, enum ns5__SmsFormat *, const char*, const char*);

#ifndef soap_read_ns5__SmsFormat
#define soap_read_ns5__SmsFormat(soap, data) ( soap_begin_recv(soap) || !soap_get_ns5__SmsFormat(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns5__DeliveryStatus
#define SOAP_TYPE_ns5__DeliveryStatus (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns5__DeliveryStatus(struct soap*, enum ns5__DeliveryStatus *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns5__DeliveryStatus(struct soap*, const char*, int, const enum ns5__DeliveryStatus *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_ns5__DeliveryStatus2s(struct soap*, enum ns5__DeliveryStatus);
SOAP_FMAC3 enum ns5__DeliveryStatus * SOAP_FMAC4 soap_in_ns5__DeliveryStatus(struct soap*, const char*, enum ns5__DeliveryStatus *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2ns5__DeliveryStatus(struct soap*, const char*, enum ns5__DeliveryStatus *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns5__DeliveryStatus(struct soap*, const enum ns5__DeliveryStatus *, const char*, const char*);

#ifndef soap_write_ns5__DeliveryStatus
#define soap_write_ns5__DeliveryStatus(soap, data) ( soap_serialize_ns5__DeliveryStatus(soap, data), soap_begin_send(soap) || soap_put_ns5__DeliveryStatus(soap, data, "ns5:DeliveryStatus", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 enum ns5__DeliveryStatus * SOAP_FMAC4 soap_get_ns5__DeliveryStatus(struct soap*, enum ns5__DeliveryStatus *, const char*, const char*);

#ifndef soap_read_ns5__DeliveryStatus
#define soap_read_ns5__DeliveryStatus(soap, data) ( soap_begin_recv(soap) || !soap_get_ns5__DeliveryStatus(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns4__TimeMetrics
#define SOAP_TYPE_ns4__TimeMetrics (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns4__TimeMetrics(struct soap*, enum ns4__TimeMetrics *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns4__TimeMetrics(struct soap*, const char*, int, const enum ns4__TimeMetrics *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_ns4__TimeMetrics2s(struct soap*, enum ns4__TimeMetrics);
SOAP_FMAC3 enum ns4__TimeMetrics * SOAP_FMAC4 soap_in_ns4__TimeMetrics(struct soap*, const char*, enum ns4__TimeMetrics *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2ns4__TimeMetrics(struct soap*, const char*, enum ns4__TimeMetrics *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns4__TimeMetrics(struct soap*, const enum ns4__TimeMetrics *, const char*, const char*);

#ifndef soap_write_ns4__TimeMetrics
#define soap_write_ns4__TimeMetrics(soap, data) ( soap_serialize_ns4__TimeMetrics(soap, data), soap_begin_send(soap) || soap_put_ns4__TimeMetrics(soap, data, "ns4:TimeMetrics", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 enum ns4__TimeMetrics * SOAP_FMAC4 soap_get_ns4__TimeMetrics(struct soap*, enum ns4__TimeMetrics *, const char*, const char*);

#ifndef soap_read_ns4__TimeMetrics
#define soap_read_ns4__TimeMetrics(soap, data) ( soap_begin_recv(soap) || !soap_get_ns4__TimeMetrics(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns4__EndReason
#define SOAP_TYPE_ns4__EndReason (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns4__EndReason(struct soap*, enum ns4__EndReason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns4__EndReason(struct soap*, const char*, int, const enum ns4__EndReason *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_ns4__EndReason2s(struct soap*, enum ns4__EndReason);
SOAP_FMAC3 enum ns4__EndReason * SOAP_FMAC4 soap_in_ns4__EndReason(struct soap*, const char*, enum ns4__EndReason *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2ns4__EndReason(struct soap*, const char*, enum ns4__EndReason *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns4__EndReason(struct soap*, const enum ns4__EndReason *, const char*, const char*);

#ifndef soap_write_ns4__EndReason
#define soap_write_ns4__EndReason(soap, data) ( soap_serialize_ns4__EndReason(soap, data), soap_begin_send(soap) || soap_put_ns4__EndReason(soap, data, "ns4:EndReason", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 enum ns4__EndReason * SOAP_FMAC4 soap_get_ns4__EndReason(struct soap*, enum ns4__EndReason *, const char*, const char*);

#ifndef soap_read_ns4__EndReason
#define soap_read_ns4__EndReason(soap, data) ( soap_begin_recv(soap) || !soap_get_ns4__EndReason(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns4__DeliveryConfirmStatus
#define SOAP_TYPE_ns4__DeliveryConfirmStatus (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns4__DeliveryConfirmStatus(struct soap*, enum ns4__DeliveryConfirmStatus *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns4__DeliveryConfirmStatus(struct soap*, const char*, int, const enum ns4__DeliveryConfirmStatus *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_ns4__DeliveryConfirmStatus2s(struct soap*, enum ns4__DeliveryConfirmStatus);
SOAP_FMAC3 enum ns4__DeliveryConfirmStatus * SOAP_FMAC4 soap_in_ns4__DeliveryConfirmStatus(struct soap*, const char*, enum ns4__DeliveryConfirmStatus *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2ns4__DeliveryConfirmStatus(struct soap*, const char*, enum ns4__DeliveryConfirmStatus *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns4__DeliveryConfirmStatus(struct soap*, const enum ns4__DeliveryConfirmStatus *, const char*, const char*);

#ifndef soap_write_ns4__DeliveryConfirmStatus
#define soap_write_ns4__DeliveryConfirmStatus(soap, data) ( soap_serialize_ns4__DeliveryConfirmStatus(soap, data), soap_begin_send(soap) || soap_put_ns4__DeliveryConfirmStatus(soap, data, "ns4:DeliveryConfirmStatus", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 enum ns4__DeliveryConfirmStatus * SOAP_FMAC4 soap_get_ns4__DeliveryConfirmStatus(struct soap*, enum ns4__DeliveryConfirmStatus *, const char*, const char*);

#ifndef soap_read_ns4__DeliveryConfirmStatus
#define soap_read_ns4__DeliveryConfirmStatus(soap, data) ( soap_begin_recv(soap) || !soap_get_ns4__DeliveryConfirmStatus(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__boolean(struct soap*, enum xsd__boolean *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__boolean(struct soap*, const char*, int, const enum xsd__boolean *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_xsd__boolean2s(struct soap*, enum xsd__boolean);
SOAP_FMAC3 enum xsd__boolean * SOAP_FMAC4 soap_in_xsd__boolean(struct soap*, const char*, enum xsd__boolean *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2xsd__boolean(struct soap*, const char*, enum xsd__boolean *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__boolean(struct soap*, const enum xsd__boolean *, const char*, const char*);

#ifndef soap_write_xsd__boolean
#define soap_write_xsd__boolean(soap, data) ( soap_serialize_xsd__boolean(soap, data), soap_begin_send(soap) || soap_put_xsd__boolean(soap, data, "xsd:boolean", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 enum xsd__boolean * SOAP_FMAC4 soap_get_xsd__boolean(struct soap*, enum xsd__boolean *, const char*, const char*);

#ifndef soap_read_xsd__boolean
#define soap_read_xsd__boolean(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__boolean(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (70)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_serialize_SOAP_ENV__Fault(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (69)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_serialize_SOAP_ENV__Reason(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (67)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_serialize_SOAP_ENV__Code(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef SOAP_TYPE___ns1__getSmsDeliveryStatus
#define SOAP_TYPE___ns1__getSmsDeliveryStatus (66)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__getSmsDeliveryStatus(struct soap*, struct __ns1__getSmsDeliveryStatus *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__getSmsDeliveryStatus(struct soap*, const struct __ns1__getSmsDeliveryStatus *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__getSmsDeliveryStatus(struct soap*, const char*, int, const struct __ns1__getSmsDeliveryStatus *, const char*);
SOAP_FMAC3 struct __ns1__getSmsDeliveryStatus * SOAP_FMAC4 soap_in___ns1__getSmsDeliveryStatus(struct soap*, const char*, struct __ns1__getSmsDeliveryStatus *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__getSmsDeliveryStatus(struct soap*, const struct __ns1__getSmsDeliveryStatus *, const char*, const char*);

#ifndef soap_write___ns1__getSmsDeliveryStatus
#define soap_write___ns1__getSmsDeliveryStatus(soap, data) ( soap_serialize___ns1__getSmsDeliveryStatus(soap, data), soap_begin_send(soap) || soap_put___ns1__getSmsDeliveryStatus(soap, data, "-ns1:getSmsDeliveryStatus", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct __ns1__getSmsDeliveryStatus * SOAP_FMAC4 soap_get___ns1__getSmsDeliveryStatus(struct soap*, struct __ns1__getSmsDeliveryStatus *, const char*, const char*);

#ifndef soap_read___ns1__getSmsDeliveryStatus
#define soap_read___ns1__getSmsDeliveryStatus(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__getSmsDeliveryStatus(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE___ns1__sendSmsRingtone
#define SOAP_TYPE___ns1__sendSmsRingtone (62)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__sendSmsRingtone(struct soap*, struct __ns1__sendSmsRingtone *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__sendSmsRingtone(struct soap*, const struct __ns1__sendSmsRingtone *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__sendSmsRingtone(struct soap*, const char*, int, const struct __ns1__sendSmsRingtone *, const char*);
SOAP_FMAC3 struct __ns1__sendSmsRingtone * SOAP_FMAC4 soap_in___ns1__sendSmsRingtone(struct soap*, const char*, struct __ns1__sendSmsRingtone *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__sendSmsRingtone(struct soap*, const struct __ns1__sendSmsRingtone *, const char*, const char*);

#ifndef soap_write___ns1__sendSmsRingtone
#define soap_write___ns1__sendSmsRingtone(soap, data) ( soap_serialize___ns1__sendSmsRingtone(soap, data), soap_begin_send(soap) || soap_put___ns1__sendSmsRingtone(soap, data, "-ns1:sendSmsRingtone", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct __ns1__sendSmsRingtone * SOAP_FMAC4 soap_get___ns1__sendSmsRingtone(struct soap*, struct __ns1__sendSmsRingtone *, const char*, const char*);

#ifndef soap_read___ns1__sendSmsRingtone
#define soap_read___ns1__sendSmsRingtone(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__sendSmsRingtone(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE___ns1__sendSmsLogo
#define SOAP_TYPE___ns1__sendSmsLogo (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__sendSmsLogo(struct soap*, struct __ns1__sendSmsLogo *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__sendSmsLogo(struct soap*, const struct __ns1__sendSmsLogo *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__sendSmsLogo(struct soap*, const char*, int, const struct __ns1__sendSmsLogo *, const char*);
SOAP_FMAC3 struct __ns1__sendSmsLogo * SOAP_FMAC4 soap_in___ns1__sendSmsLogo(struct soap*, const char*, struct __ns1__sendSmsLogo *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__sendSmsLogo(struct soap*, const struct __ns1__sendSmsLogo *, const char*, const char*);

#ifndef soap_write___ns1__sendSmsLogo
#define soap_write___ns1__sendSmsLogo(soap, data) ( soap_serialize___ns1__sendSmsLogo(soap, data), soap_begin_send(soap) || soap_put___ns1__sendSmsLogo(soap, data, "-ns1:sendSmsLogo", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct __ns1__sendSmsLogo * SOAP_FMAC4 soap_get___ns1__sendSmsLogo(struct soap*, struct __ns1__sendSmsLogo *, const char*, const char*);

#ifndef soap_read___ns1__sendSmsLogo
#define soap_read___ns1__sendSmsLogo(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__sendSmsLogo(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE___ns1__sendSms
#define SOAP_TYPE___ns1__sendSms (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__sendSms(struct soap*, struct __ns1__sendSms *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__sendSms(struct soap*, const struct __ns1__sendSms *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__sendSms(struct soap*, const char*, int, const struct __ns1__sendSms *, const char*);
SOAP_FMAC3 struct __ns1__sendSms * SOAP_FMAC4 soap_in___ns1__sendSms(struct soap*, const char*, struct __ns1__sendSms *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__sendSms(struct soap*, const struct __ns1__sendSms *, const char*, const char*);

#ifndef soap_write___ns1__sendSms
#define soap_write___ns1__sendSms(soap, data) ( soap_serialize___ns1__sendSms(soap, data), soap_begin_send(soap) || soap_put___ns1__sendSms(soap, data, "-ns1:sendSms", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct __ns1__sendSms * SOAP_FMAC4 soap_get___ns1__sendSms(struct soap*, struct __ns1__sendSms *, const char*, const char*);

#ifndef soap_read___ns1__sendSms
#define soap_read___ns1__sendSms(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__sendSms(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_serialize_SOAP_ENV__Detail(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_serialize_SOAP_ENV__Header(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef SOAP_TYPE_ns5__SmsMessage
#define SOAP_TYPE_ns5__SmsMessage (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns5__SmsMessage(struct soap*, struct ns5__SmsMessage *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns5__SmsMessage(struct soap*, const struct ns5__SmsMessage *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns5__SmsMessage(struct soap*, const char*, int, const struct ns5__SmsMessage *, const char*);
SOAP_FMAC3 struct ns5__SmsMessage * SOAP_FMAC4 soap_in_ns5__SmsMessage(struct soap*, const char*, struct ns5__SmsMessage *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns5__SmsMessage(struct soap*, const struct ns5__SmsMessage *, const char*, const char*);

#ifndef soap_write_ns5__SmsMessage
#define soap_write_ns5__SmsMessage(soap, data) ( soap_serialize_ns5__SmsMessage(soap, data), soap_begin_send(soap) || soap_put_ns5__SmsMessage(soap, data, "ns5:SmsMessage", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns5__SmsMessage * SOAP_FMAC4 soap_get_ns5__SmsMessage(struct soap*, struct ns5__SmsMessage *, const char*, const char*);

#ifndef soap_read_ns5__SmsMessage
#define soap_read_ns5__SmsMessage(soap, data) ( soap_begin_recv(soap) || !soap_get_ns5__SmsMessage(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns4__PolicyException
#define SOAP_TYPE_ns4__PolicyException (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns4__PolicyException(struct soap*, struct ns4__PolicyException *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns4__PolicyException(struct soap*, const struct ns4__PolicyException *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns4__PolicyException(struct soap*, const char*, int, const struct ns4__PolicyException *, const char*);
SOAP_FMAC3 struct ns4__PolicyException * SOAP_FMAC4 soap_in_ns4__PolicyException(struct soap*, const char*, struct ns4__PolicyException *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns4__PolicyException(struct soap*, const struct ns4__PolicyException *, const char*, const char*);

#ifndef soap_write_ns4__PolicyException
#define soap_write_ns4__PolicyException(soap, data) ( soap_serialize_ns4__PolicyException(soap, data), soap_begin_send(soap) || soap_put_ns4__PolicyException(soap, data, "ns4:PolicyException", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns4__PolicyException * SOAP_FMAC4 soap_get_ns4__PolicyException(struct soap*, struct ns4__PolicyException *, const char*, const char*);

#ifndef soap_read_ns4__PolicyException
#define soap_read_ns4__PolicyException(soap, data) ( soap_begin_recv(soap) || !soap_get_ns4__PolicyException(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns4__ServiceException
#define SOAP_TYPE_ns4__ServiceException (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns4__ServiceException(struct soap*, struct ns4__ServiceException *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns4__ServiceException(struct soap*, const struct ns4__ServiceException *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns4__ServiceException(struct soap*, const char*, int, const struct ns4__ServiceException *, const char*);
SOAP_FMAC3 struct ns4__ServiceException * SOAP_FMAC4 soap_in_ns4__ServiceException(struct soap*, const char*, struct ns4__ServiceException *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns4__ServiceException(struct soap*, const struct ns4__ServiceException *, const char*, const char*);

#ifndef soap_write_ns4__ServiceException
#define soap_write_ns4__ServiceException(soap, data) ( soap_serialize_ns4__ServiceException(soap, data), soap_begin_send(soap) || soap_put_ns4__ServiceException(soap, data, "ns4:ServiceException", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns4__ServiceException * SOAP_FMAC4 soap_get_ns4__ServiceException(struct soap*, struct ns4__ServiceException *, const char*, const char*);

#ifndef soap_read_ns4__ServiceException
#define soap_read_ns4__ServiceException(soap, data) ( soap_begin_recv(soap) || !soap_get_ns4__ServiceException(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns4__ServiceError
#define SOAP_TYPE_ns4__ServiceError (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns4__ServiceError(struct soap*, struct ns4__ServiceError *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns4__ServiceError(struct soap*, const struct ns4__ServiceError *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns4__ServiceError(struct soap*, const char*, int, const struct ns4__ServiceError *, const char*);
SOAP_FMAC3 struct ns4__ServiceError * SOAP_FMAC4 soap_in_ns4__ServiceError(struct soap*, const char*, struct ns4__ServiceError *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns4__ServiceError(struct soap*, const struct ns4__ServiceError *, const char*, const char*);

#ifndef soap_write_ns4__ServiceError
#define soap_write_ns4__ServiceError(soap, data) ( soap_serialize_ns4__ServiceError(soap, data), soap_begin_send(soap) || soap_put_ns4__ServiceError(soap, data, "ns4:ServiceError", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns4__ServiceError * SOAP_FMAC4 soap_get_ns4__ServiceError(struct soap*, struct ns4__ServiceError *, const char*, const char*);

#ifndef soap_read_ns4__ServiceError
#define soap_read_ns4__ServiceError(soap, data) ( soap_begin_recv(soap) || !soap_get_ns4__ServiceError(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns4__TimeMetric
#define SOAP_TYPE_ns4__TimeMetric (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns4__TimeMetric(struct soap*, struct ns4__TimeMetric *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns4__TimeMetric(struct soap*, const struct ns4__TimeMetric *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns4__TimeMetric(struct soap*, const char*, int, const struct ns4__TimeMetric *, const char*);
SOAP_FMAC3 struct ns4__TimeMetric * SOAP_FMAC4 soap_in_ns4__TimeMetric(struct soap*, const char*, struct ns4__TimeMetric *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns4__TimeMetric(struct soap*, const struct ns4__TimeMetric *, const char*, const char*);

#ifndef soap_write_ns4__TimeMetric
#define soap_write_ns4__TimeMetric(soap, data) ( soap_serialize_ns4__TimeMetric(soap, data), soap_begin_send(soap) || soap_put_ns4__TimeMetric(soap, data, "ns4:TimeMetric", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns4__TimeMetric * SOAP_FMAC4 soap_get_ns4__TimeMetric(struct soap*, struct ns4__TimeMetric *, const char*, const char*);

#ifndef soap_read_ns4__TimeMetric
#define soap_read_ns4__TimeMetric(soap, data) ( soap_begin_recv(soap) || !soap_get_ns4__TimeMetric(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns4__NotifySOAPHeader
#define SOAP_TYPE_ns4__NotifySOAPHeader (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns4__NotifySOAPHeader(struct soap*, struct ns4__NotifySOAPHeader *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns4__NotifySOAPHeader(struct soap*, const struct ns4__NotifySOAPHeader *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns4__NotifySOAPHeader(struct soap*, const char*, int, const struct ns4__NotifySOAPHeader *, const char*);
SOAP_FMAC3 struct ns4__NotifySOAPHeader * SOAP_FMAC4 soap_in_ns4__NotifySOAPHeader(struct soap*, const char*, struct ns4__NotifySOAPHeader *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns4__NotifySOAPHeader(struct soap*, const struct ns4__NotifySOAPHeader *, const char*, const char*);

#ifndef soap_write_ns4__NotifySOAPHeader
#define soap_write_ns4__NotifySOAPHeader(soap, data) ( soap_serialize_ns4__NotifySOAPHeader(soap, data), soap_begin_send(soap) || soap_put_ns4__NotifySOAPHeader(soap, data, "ns4:NotifySOAPHeader", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns4__NotifySOAPHeader * SOAP_FMAC4 soap_get_ns4__NotifySOAPHeader(struct soap*, struct ns4__NotifySOAPHeader *, const char*, const char*);

#ifndef soap_read_ns4__NotifySOAPHeader
#define soap_read_ns4__NotifySOAPHeader(soap, data) ( soap_begin_recv(soap) || !soap_get_ns4__NotifySOAPHeader(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns4__RequestSOAPHeader
#define SOAP_TYPE_ns4__RequestSOAPHeader (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns4__RequestSOAPHeader(struct soap*, struct ns4__RequestSOAPHeader *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns4__RequestSOAPHeader(struct soap*, const struct ns4__RequestSOAPHeader *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns4__RequestSOAPHeader(struct soap*, const char*, int, const struct ns4__RequestSOAPHeader *, const char*);
SOAP_FMAC3 struct ns4__RequestSOAPHeader * SOAP_FMAC4 soap_in_ns4__RequestSOAPHeader(struct soap*, const char*, struct ns4__RequestSOAPHeader *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns4__RequestSOAPHeader(struct soap*, const struct ns4__RequestSOAPHeader *, const char*, const char*);

#ifndef soap_write_ns4__RequestSOAPHeader
#define soap_write_ns4__RequestSOAPHeader(soap, data) ( soap_serialize_ns4__RequestSOAPHeader(soap, data), soap_begin_send(soap) || soap_put_ns4__RequestSOAPHeader(soap, data, "ns4:RequestSOAPHeader", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns4__RequestSOAPHeader * SOAP_FMAC4 soap_get_ns4__RequestSOAPHeader(struct soap*, struct ns4__RequestSOAPHeader *, const char*, const char*);

#ifndef soap_read_ns4__RequestSOAPHeader
#define soap_read_ns4__RequestSOAPHeader(soap, data) ( soap_begin_recv(soap) || !soap_get_ns4__RequestSOAPHeader(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns5__DeliveryInformation
#define SOAP_TYPE_ns5__DeliveryInformation (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns5__DeliveryInformation(struct soap*, struct ns5__DeliveryInformation *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns5__DeliveryInformation(struct soap*, const struct ns5__DeliveryInformation *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns5__DeliveryInformation(struct soap*, const char*, int, const struct ns5__DeliveryInformation *, const char*);
SOAP_FMAC3 struct ns5__DeliveryInformation * SOAP_FMAC4 soap_in_ns5__DeliveryInformation(struct soap*, const char*, struct ns5__DeliveryInformation *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns5__DeliveryInformation(struct soap*, const struct ns5__DeliveryInformation *, const char*, const char*);

#ifndef soap_write_ns5__DeliveryInformation
#define soap_write_ns5__DeliveryInformation(soap, data) ( soap_serialize_ns5__DeliveryInformation(soap, data), soap_begin_send(soap) || soap_put_ns5__DeliveryInformation(soap, data, "ns5:DeliveryInformation", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns5__DeliveryInformation * SOAP_FMAC4 soap_get_ns5__DeliveryInformation(struct soap*, struct ns5__DeliveryInformation *, const char*, const char*);

#ifndef soap_read_ns5__DeliveryInformation
#define soap_read_ns5__DeliveryInformation(soap, data) ( soap_begin_recv(soap) || !soap_get_ns5__DeliveryInformation(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns2__getSmsDeliveryStatusResponse
#define SOAP_TYPE_ns2__getSmsDeliveryStatusResponse (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__getSmsDeliveryStatusResponse(struct soap*, struct ns2__getSmsDeliveryStatusResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__getSmsDeliveryStatusResponse(struct soap*, const struct ns2__getSmsDeliveryStatusResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__getSmsDeliveryStatusResponse(struct soap*, const char*, int, const struct ns2__getSmsDeliveryStatusResponse *, const char*);
SOAP_FMAC3 struct ns2__getSmsDeliveryStatusResponse * SOAP_FMAC4 soap_in_ns2__getSmsDeliveryStatusResponse(struct soap*, const char*, struct ns2__getSmsDeliveryStatusResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__getSmsDeliveryStatusResponse(struct soap*, const struct ns2__getSmsDeliveryStatusResponse *, const char*, const char*);

#ifndef soap_write_ns2__getSmsDeliveryStatusResponse
#define soap_write_ns2__getSmsDeliveryStatusResponse(soap, data) ( soap_serialize_ns2__getSmsDeliveryStatusResponse(soap, data), soap_begin_send(soap) || soap_put_ns2__getSmsDeliveryStatusResponse(soap, data, "ns2:getSmsDeliveryStatusResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__getSmsDeliveryStatusResponse * SOAP_FMAC4 soap_get_ns2__getSmsDeliveryStatusResponse(struct soap*, struct ns2__getSmsDeliveryStatusResponse *, const char*, const char*);

#ifndef soap_read_ns2__getSmsDeliveryStatusResponse
#define soap_read_ns2__getSmsDeliveryStatusResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__getSmsDeliveryStatusResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns2__getSmsDeliveryStatus
#define SOAP_TYPE_ns2__getSmsDeliveryStatus (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__getSmsDeliveryStatus(struct soap*, struct ns2__getSmsDeliveryStatus *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__getSmsDeliveryStatus(struct soap*, const struct ns2__getSmsDeliveryStatus *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__getSmsDeliveryStatus(struct soap*, const char*, int, const struct ns2__getSmsDeliveryStatus *, const char*);
SOAP_FMAC3 struct ns2__getSmsDeliveryStatus * SOAP_FMAC4 soap_in_ns2__getSmsDeliveryStatus(struct soap*, const char*, struct ns2__getSmsDeliveryStatus *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__getSmsDeliveryStatus(struct soap*, const struct ns2__getSmsDeliveryStatus *, const char*, const char*);

#ifndef soap_write_ns2__getSmsDeliveryStatus
#define soap_write_ns2__getSmsDeliveryStatus(soap, data) ( soap_serialize_ns2__getSmsDeliveryStatus(soap, data), soap_begin_send(soap) || soap_put_ns2__getSmsDeliveryStatus(soap, data, "ns2:getSmsDeliveryStatus", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__getSmsDeliveryStatus * SOAP_FMAC4 soap_get_ns2__getSmsDeliveryStatus(struct soap*, struct ns2__getSmsDeliveryStatus *, const char*, const char*);

#ifndef soap_read_ns2__getSmsDeliveryStatus
#define soap_read_ns2__getSmsDeliveryStatus(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__getSmsDeliveryStatus(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns2__sendSmsRingtoneResponse
#define SOAP_TYPE_ns2__sendSmsRingtoneResponse (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__sendSmsRingtoneResponse(struct soap*, struct ns2__sendSmsRingtoneResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__sendSmsRingtoneResponse(struct soap*, const struct ns2__sendSmsRingtoneResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__sendSmsRingtoneResponse(struct soap*, const char*, int, const struct ns2__sendSmsRingtoneResponse *, const char*);
SOAP_FMAC3 struct ns2__sendSmsRingtoneResponse * SOAP_FMAC4 soap_in_ns2__sendSmsRingtoneResponse(struct soap*, const char*, struct ns2__sendSmsRingtoneResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__sendSmsRingtoneResponse(struct soap*, const struct ns2__sendSmsRingtoneResponse *, const char*, const char*);

#ifndef soap_write_ns2__sendSmsRingtoneResponse
#define soap_write_ns2__sendSmsRingtoneResponse(soap, data) ( soap_serialize_ns2__sendSmsRingtoneResponse(soap, data), soap_begin_send(soap) || soap_put_ns2__sendSmsRingtoneResponse(soap, data, "ns2:sendSmsRingtoneResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__sendSmsRingtoneResponse * SOAP_FMAC4 soap_get_ns2__sendSmsRingtoneResponse(struct soap*, struct ns2__sendSmsRingtoneResponse *, const char*, const char*);

#ifndef soap_read_ns2__sendSmsRingtoneResponse
#define soap_read_ns2__sendSmsRingtoneResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__sendSmsRingtoneResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns2__sendSmsRingtone
#define SOAP_TYPE_ns2__sendSmsRingtone (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__sendSmsRingtone(struct soap*, struct ns2__sendSmsRingtone *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__sendSmsRingtone(struct soap*, const struct ns2__sendSmsRingtone *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__sendSmsRingtone(struct soap*, const char*, int, const struct ns2__sendSmsRingtone *, const char*);
SOAP_FMAC3 struct ns2__sendSmsRingtone * SOAP_FMAC4 soap_in_ns2__sendSmsRingtone(struct soap*, const char*, struct ns2__sendSmsRingtone *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__sendSmsRingtone(struct soap*, const struct ns2__sendSmsRingtone *, const char*, const char*);

#ifndef soap_write_ns2__sendSmsRingtone
#define soap_write_ns2__sendSmsRingtone(soap, data) ( soap_serialize_ns2__sendSmsRingtone(soap, data), soap_begin_send(soap) || soap_put_ns2__sendSmsRingtone(soap, data, "ns2:sendSmsRingtone", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__sendSmsRingtone * SOAP_FMAC4 soap_get_ns2__sendSmsRingtone(struct soap*, struct ns2__sendSmsRingtone *, const char*, const char*);

#ifndef soap_read_ns2__sendSmsRingtone
#define soap_read_ns2__sendSmsRingtone(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__sendSmsRingtone(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns2__sendSmsLogoResponse
#define SOAP_TYPE_ns2__sendSmsLogoResponse (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__sendSmsLogoResponse(struct soap*, struct ns2__sendSmsLogoResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__sendSmsLogoResponse(struct soap*, const struct ns2__sendSmsLogoResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__sendSmsLogoResponse(struct soap*, const char*, int, const struct ns2__sendSmsLogoResponse *, const char*);
SOAP_FMAC3 struct ns2__sendSmsLogoResponse * SOAP_FMAC4 soap_in_ns2__sendSmsLogoResponse(struct soap*, const char*, struct ns2__sendSmsLogoResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__sendSmsLogoResponse(struct soap*, const struct ns2__sendSmsLogoResponse *, const char*, const char*);

#ifndef soap_write_ns2__sendSmsLogoResponse
#define soap_write_ns2__sendSmsLogoResponse(soap, data) ( soap_serialize_ns2__sendSmsLogoResponse(soap, data), soap_begin_send(soap) || soap_put_ns2__sendSmsLogoResponse(soap, data, "ns2:sendSmsLogoResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__sendSmsLogoResponse * SOAP_FMAC4 soap_get_ns2__sendSmsLogoResponse(struct soap*, struct ns2__sendSmsLogoResponse *, const char*, const char*);

#ifndef soap_read_ns2__sendSmsLogoResponse
#define soap_read_ns2__sendSmsLogoResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__sendSmsLogoResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns2__sendSmsLogo
#define SOAP_TYPE_ns2__sendSmsLogo (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__sendSmsLogo(struct soap*, struct ns2__sendSmsLogo *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__sendSmsLogo(struct soap*, const struct ns2__sendSmsLogo *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__sendSmsLogo(struct soap*, const char*, int, const struct ns2__sendSmsLogo *, const char*);
SOAP_FMAC3 struct ns2__sendSmsLogo * SOAP_FMAC4 soap_in_ns2__sendSmsLogo(struct soap*, const char*, struct ns2__sendSmsLogo *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__sendSmsLogo(struct soap*, const struct ns2__sendSmsLogo *, const char*, const char*);

#ifndef soap_write_ns2__sendSmsLogo
#define soap_write_ns2__sendSmsLogo(soap, data) ( soap_serialize_ns2__sendSmsLogo(soap, data), soap_begin_send(soap) || soap_put_ns2__sendSmsLogo(soap, data, "ns2:sendSmsLogo", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__sendSmsLogo * SOAP_FMAC4 soap_get_ns2__sendSmsLogo(struct soap*, struct ns2__sendSmsLogo *, const char*, const char*);

#ifndef soap_read_ns2__sendSmsLogo
#define soap_read_ns2__sendSmsLogo(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__sendSmsLogo(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns2__sendSmsResponse
#define SOAP_TYPE_ns2__sendSmsResponse (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__sendSmsResponse(struct soap*, struct ns2__sendSmsResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__sendSmsResponse(struct soap*, const struct ns2__sendSmsResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__sendSmsResponse(struct soap*, const char*, int, const struct ns2__sendSmsResponse *, const char*);
SOAP_FMAC3 struct ns2__sendSmsResponse * SOAP_FMAC4 soap_in_ns2__sendSmsResponse(struct soap*, const char*, struct ns2__sendSmsResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__sendSmsResponse(struct soap*, const struct ns2__sendSmsResponse *, const char*, const char*);

#ifndef soap_write_ns2__sendSmsResponse
#define soap_write_ns2__sendSmsResponse(soap, data) ( soap_serialize_ns2__sendSmsResponse(soap, data), soap_begin_send(soap) || soap_put_ns2__sendSmsResponse(soap, data, "ns2:sendSmsResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__sendSmsResponse * SOAP_FMAC4 soap_get_ns2__sendSmsResponse(struct soap*, struct ns2__sendSmsResponse *, const char*, const char*);

#ifndef soap_read_ns2__sendSmsResponse
#define soap_read_ns2__sendSmsResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__sendSmsResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns4__SimpleReference
#define SOAP_TYPE_ns4__SimpleReference (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns4__SimpleReference(struct soap*, struct ns4__SimpleReference *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns4__SimpleReference(struct soap*, const struct ns4__SimpleReference *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns4__SimpleReference(struct soap*, const char*, int, const struct ns4__SimpleReference *, const char*);
SOAP_FMAC3 struct ns4__SimpleReference * SOAP_FMAC4 soap_in_ns4__SimpleReference(struct soap*, const char*, struct ns4__SimpleReference *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns4__SimpleReference(struct soap*, const struct ns4__SimpleReference *, const char*, const char*);

#ifndef soap_write_ns4__SimpleReference
#define soap_write_ns4__SimpleReference(soap, data) ( soap_serialize_ns4__SimpleReference(soap, data), soap_begin_send(soap) || soap_put_ns4__SimpleReference(soap, data, "ns4:SimpleReference", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns4__SimpleReference * SOAP_FMAC4 soap_get_ns4__SimpleReference(struct soap*, struct ns4__SimpleReference *, const char*, const char*);

#ifndef soap_read_ns4__SimpleReference
#define soap_read_ns4__SimpleReference(soap, data) ( soap_begin_recv(soap) || !soap_get_ns4__SimpleReference(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns4__ChargingInformation
#define SOAP_TYPE_ns4__ChargingInformation (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns4__ChargingInformation(struct soap*, struct ns4__ChargingInformation *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns4__ChargingInformation(struct soap*, const struct ns4__ChargingInformation *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns4__ChargingInformation(struct soap*, const char*, int, const struct ns4__ChargingInformation *, const char*);
SOAP_FMAC3 struct ns4__ChargingInformation * SOAP_FMAC4 soap_in_ns4__ChargingInformation(struct soap*, const char*, struct ns4__ChargingInformation *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns4__ChargingInformation(struct soap*, const struct ns4__ChargingInformation *, const char*, const char*);

#ifndef soap_write_ns4__ChargingInformation
#define soap_write_ns4__ChargingInformation(soap, data) ( soap_serialize_ns4__ChargingInformation(soap, data), soap_begin_send(soap) || soap_put_ns4__ChargingInformation(soap, data, "ns4:ChargingInformation", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns4__ChargingInformation * SOAP_FMAC4 soap_get_ns4__ChargingInformation(struct soap*, struct ns4__ChargingInformation *, const char*, const char*);

#ifndef soap_read_ns4__ChargingInformation
#define soap_read_ns4__ChargingInformation(soap, data) ( soap_begin_recv(soap) || !soap_get_ns4__ChargingInformation(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns2__sendSms
#define SOAP_TYPE_ns2__sendSms (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__sendSms(struct soap*, struct ns2__sendSms *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__sendSms(struct soap*, const struct ns2__sendSms *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__sendSms(struct soap*, const char*, int, const struct ns2__sendSms *, const char*);
SOAP_FMAC3 struct ns2__sendSms * SOAP_FMAC4 soap_in_ns2__sendSms(struct soap*, const char*, struct ns2__sendSms *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__sendSms(struct soap*, const struct ns2__sendSms *, const char*, const char*);

#ifndef soap_write_ns2__sendSms
#define soap_write_ns2__sendSms(soap, data) ( soap_serialize_ns2__sendSms(soap, data), soap_begin_send(soap) || soap_put_ns2__sendSms(soap, data, "ns2:sendSms", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__sendSms * SOAP_FMAC4 soap_get_ns2__sendSms(struct soap*, struct ns2__sendSms *, const char*, const char*);

#ifndef soap_read_ns2__sendSms
#define soap_read_ns2__sendSms(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__sendSms(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_xsd__base64Binary
#define SOAP_TYPE_xsd__base64Binary (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__base64Binary(struct soap*, struct xsd__base64Binary *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__base64Binary(struct soap*, struct xsd__base64Binary const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__base64Binary(struct soap*, const char*, int, const struct xsd__base64Binary *, const char*);
SOAP_FMAC3 struct xsd__base64Binary * SOAP_FMAC4 soap_in_xsd__base64Binary(struct soap*, const char*, struct xsd__base64Binary *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__base64Binary(struct soap*, const struct xsd__base64Binary *, const char*, const char*);

#ifndef soap_write_xsd__base64Binary
#define soap_write_xsd__base64Binary(soap, data) ( soap_serialize_xsd__base64Binary(soap, data), soap_begin_send(soap) || soap_put_xsd__base64Binary(soap, data, "xsd:base64Binary", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct xsd__base64Binary * SOAP_FMAC4 soap_get_xsd__base64Binary(struct soap*, struct xsd__base64Binary *, const char*, const char*);

#ifndef soap_read_xsd__base64Binary
#define soap_read_xsd__base64Binary(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__base64Binary(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (72)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_serialize_PointerToSOAP_ENV__Reason(soap, data), soap_begin_send(soap) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (71)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_serialize_PointerToSOAP_ENV__Detail(soap, data), soap_begin_send(soap) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (68)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_serialize_PointerToSOAP_ENV__Code(soap, data), soap_begin_send(soap) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef SOAP_TYPE_PointerTons2__getSmsDeliveryStatusResponse
#define SOAP_TYPE_PointerTons2__getSmsDeliveryStatusResponse (64)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__getSmsDeliveryStatusResponse(struct soap*, struct ns2__getSmsDeliveryStatusResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__getSmsDeliveryStatusResponse(struct soap*, const char *, int, struct ns2__getSmsDeliveryStatusResponse *const*, const char *);
SOAP_FMAC3 struct ns2__getSmsDeliveryStatusResponse ** SOAP_FMAC4 soap_in_PointerTons2__getSmsDeliveryStatusResponse(struct soap*, const char*, struct ns2__getSmsDeliveryStatusResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__getSmsDeliveryStatusResponse(struct soap*, struct ns2__getSmsDeliveryStatusResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__getSmsDeliveryStatusResponse
#define soap_write_PointerTons2__getSmsDeliveryStatusResponse(soap, data) ( soap_serialize_PointerTons2__getSmsDeliveryStatusResponse(soap, data), soap_begin_send(soap) || soap_put_PointerTons2__getSmsDeliveryStatusResponse(soap, data, "ns2:getSmsDeliveryStatusResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__getSmsDeliveryStatusResponse ** SOAP_FMAC4 soap_get_PointerTons2__getSmsDeliveryStatusResponse(struct soap*, struct ns2__getSmsDeliveryStatusResponse **, const char*, const char*);

#ifndef soap_read_PointerTons2__getSmsDeliveryStatusResponse
#define soap_read_PointerTons2__getSmsDeliveryStatusResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__getSmsDeliveryStatusResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons2__getSmsDeliveryStatus
#define SOAP_TYPE_PointerTons2__getSmsDeliveryStatus (63)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__getSmsDeliveryStatus(struct soap*, struct ns2__getSmsDeliveryStatus *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__getSmsDeliveryStatus(struct soap*, const char *, int, struct ns2__getSmsDeliveryStatus *const*, const char *);
SOAP_FMAC3 struct ns2__getSmsDeliveryStatus ** SOAP_FMAC4 soap_in_PointerTons2__getSmsDeliveryStatus(struct soap*, const char*, struct ns2__getSmsDeliveryStatus **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__getSmsDeliveryStatus(struct soap*, struct ns2__getSmsDeliveryStatus *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__getSmsDeliveryStatus
#define soap_write_PointerTons2__getSmsDeliveryStatus(soap, data) ( soap_serialize_PointerTons2__getSmsDeliveryStatus(soap, data), soap_begin_send(soap) || soap_put_PointerTons2__getSmsDeliveryStatus(soap, data, "ns2:getSmsDeliveryStatus", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__getSmsDeliveryStatus ** SOAP_FMAC4 soap_get_PointerTons2__getSmsDeliveryStatus(struct soap*, struct ns2__getSmsDeliveryStatus **, const char*, const char*);

#ifndef soap_read_PointerTons2__getSmsDeliveryStatus
#define soap_read_PointerTons2__getSmsDeliveryStatus(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__getSmsDeliveryStatus(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons2__sendSmsRingtoneResponse
#define SOAP_TYPE_PointerTons2__sendSmsRingtoneResponse (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__sendSmsRingtoneResponse(struct soap*, struct ns2__sendSmsRingtoneResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__sendSmsRingtoneResponse(struct soap*, const char *, int, struct ns2__sendSmsRingtoneResponse *const*, const char *);
SOAP_FMAC3 struct ns2__sendSmsRingtoneResponse ** SOAP_FMAC4 soap_in_PointerTons2__sendSmsRingtoneResponse(struct soap*, const char*, struct ns2__sendSmsRingtoneResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__sendSmsRingtoneResponse(struct soap*, struct ns2__sendSmsRingtoneResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__sendSmsRingtoneResponse
#define soap_write_PointerTons2__sendSmsRingtoneResponse(soap, data) ( soap_serialize_PointerTons2__sendSmsRingtoneResponse(soap, data), soap_begin_send(soap) || soap_put_PointerTons2__sendSmsRingtoneResponse(soap, data, "ns2:sendSmsRingtoneResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__sendSmsRingtoneResponse ** SOAP_FMAC4 soap_get_PointerTons2__sendSmsRingtoneResponse(struct soap*, struct ns2__sendSmsRingtoneResponse **, const char*, const char*);

#ifndef soap_read_PointerTons2__sendSmsRingtoneResponse
#define soap_read_PointerTons2__sendSmsRingtoneResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__sendSmsRingtoneResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons2__sendSmsRingtone
#define SOAP_TYPE_PointerTons2__sendSmsRingtone (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__sendSmsRingtone(struct soap*, struct ns2__sendSmsRingtone *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__sendSmsRingtone(struct soap*, const char *, int, struct ns2__sendSmsRingtone *const*, const char *);
SOAP_FMAC3 struct ns2__sendSmsRingtone ** SOAP_FMAC4 soap_in_PointerTons2__sendSmsRingtone(struct soap*, const char*, struct ns2__sendSmsRingtone **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__sendSmsRingtone(struct soap*, struct ns2__sendSmsRingtone *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__sendSmsRingtone
#define soap_write_PointerTons2__sendSmsRingtone(soap, data) ( soap_serialize_PointerTons2__sendSmsRingtone(soap, data), soap_begin_send(soap) || soap_put_PointerTons2__sendSmsRingtone(soap, data, "ns2:sendSmsRingtone", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__sendSmsRingtone ** SOAP_FMAC4 soap_get_PointerTons2__sendSmsRingtone(struct soap*, struct ns2__sendSmsRingtone **, const char*, const char*);

#ifndef soap_read_PointerTons2__sendSmsRingtone
#define soap_read_PointerTons2__sendSmsRingtone(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__sendSmsRingtone(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons2__sendSmsLogoResponse
#define SOAP_TYPE_PointerTons2__sendSmsLogoResponse (56)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__sendSmsLogoResponse(struct soap*, struct ns2__sendSmsLogoResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__sendSmsLogoResponse(struct soap*, const char *, int, struct ns2__sendSmsLogoResponse *const*, const char *);
SOAP_FMAC3 struct ns2__sendSmsLogoResponse ** SOAP_FMAC4 soap_in_PointerTons2__sendSmsLogoResponse(struct soap*, const char*, struct ns2__sendSmsLogoResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__sendSmsLogoResponse(struct soap*, struct ns2__sendSmsLogoResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__sendSmsLogoResponse
#define soap_write_PointerTons2__sendSmsLogoResponse(soap, data) ( soap_serialize_PointerTons2__sendSmsLogoResponse(soap, data), soap_begin_send(soap) || soap_put_PointerTons2__sendSmsLogoResponse(soap, data, "ns2:sendSmsLogoResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__sendSmsLogoResponse ** SOAP_FMAC4 soap_get_PointerTons2__sendSmsLogoResponse(struct soap*, struct ns2__sendSmsLogoResponse **, const char*, const char*);

#ifndef soap_read_PointerTons2__sendSmsLogoResponse
#define soap_read_PointerTons2__sendSmsLogoResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__sendSmsLogoResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons2__sendSmsLogo
#define SOAP_TYPE_PointerTons2__sendSmsLogo (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__sendSmsLogo(struct soap*, struct ns2__sendSmsLogo *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__sendSmsLogo(struct soap*, const char *, int, struct ns2__sendSmsLogo *const*, const char *);
SOAP_FMAC3 struct ns2__sendSmsLogo ** SOAP_FMAC4 soap_in_PointerTons2__sendSmsLogo(struct soap*, const char*, struct ns2__sendSmsLogo **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__sendSmsLogo(struct soap*, struct ns2__sendSmsLogo *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__sendSmsLogo
#define soap_write_PointerTons2__sendSmsLogo(soap, data) ( soap_serialize_PointerTons2__sendSmsLogo(soap, data), soap_begin_send(soap) || soap_put_PointerTons2__sendSmsLogo(soap, data, "ns2:sendSmsLogo", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__sendSmsLogo ** SOAP_FMAC4 soap_get_PointerTons2__sendSmsLogo(struct soap*, struct ns2__sendSmsLogo **, const char*, const char*);

#ifndef soap_read_PointerTons2__sendSmsLogo
#define soap_read_PointerTons2__sendSmsLogo(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__sendSmsLogo(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons2__sendSmsResponse
#define SOAP_TYPE_PointerTons2__sendSmsResponse (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__sendSmsResponse(struct soap*, struct ns2__sendSmsResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__sendSmsResponse(struct soap*, const char *, int, struct ns2__sendSmsResponse *const*, const char *);
SOAP_FMAC3 struct ns2__sendSmsResponse ** SOAP_FMAC4 soap_in_PointerTons2__sendSmsResponse(struct soap*, const char*, struct ns2__sendSmsResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__sendSmsResponse(struct soap*, struct ns2__sendSmsResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__sendSmsResponse
#define soap_write_PointerTons2__sendSmsResponse(soap, data) ( soap_serialize_PointerTons2__sendSmsResponse(soap, data), soap_begin_send(soap) || soap_put_PointerTons2__sendSmsResponse(soap, data, "ns2:sendSmsResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__sendSmsResponse ** SOAP_FMAC4 soap_get_PointerTons2__sendSmsResponse(struct soap*, struct ns2__sendSmsResponse **, const char*, const char*);

#ifndef soap_read_PointerTons2__sendSmsResponse
#define soap_read_PointerTons2__sendSmsResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__sendSmsResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons2__sendSms
#define SOAP_TYPE_PointerTons2__sendSms (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__sendSms(struct soap*, struct ns2__sendSms *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__sendSms(struct soap*, const char *, int, struct ns2__sendSms *const*, const char *);
SOAP_FMAC3 struct ns2__sendSms ** SOAP_FMAC4 soap_in_PointerTons2__sendSms(struct soap*, const char*, struct ns2__sendSms **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__sendSms(struct soap*, struct ns2__sendSms *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__sendSms
#define soap_write_PointerTons2__sendSms(soap, data) ( soap_serialize_PointerTons2__sendSms(soap, data), soap_begin_send(soap) || soap_put_PointerTons2__sendSms(soap, data, "ns2:sendSms", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns2__sendSms ** SOAP_FMAC4 soap_get_PointerTons2__sendSms(struct soap*, struct ns2__sendSms **, const char*, const char*);

#ifndef soap_read_PointerTons2__sendSms
#define soap_read_PointerTons2__sendSms(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__sendSms(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons4__ServiceException
#define SOAP_TYPE_PointerTons4__ServiceException (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons4__ServiceException(struct soap*, struct ns4__ServiceException *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons4__ServiceException(struct soap*, const char *, int, struct ns4__ServiceException *const*, const char *);
SOAP_FMAC3 struct ns4__ServiceException ** SOAP_FMAC4 soap_in_PointerTons4__ServiceException(struct soap*, const char*, struct ns4__ServiceException **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons4__ServiceException(struct soap*, struct ns4__ServiceException *const*, const char*, const char*);

#ifndef soap_write_PointerTons4__ServiceException
#define soap_write_PointerTons4__ServiceException(soap, data) ( soap_serialize_PointerTons4__ServiceException(soap, data), soap_begin_send(soap) || soap_put_PointerTons4__ServiceException(soap, data, "ns4:ServiceException", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns4__ServiceException ** SOAP_FMAC4 soap_get_PointerTons4__ServiceException(struct soap*, struct ns4__ServiceException **, const char*, const char*);

#ifndef soap_read_PointerTons4__ServiceException
#define soap_read_PointerTons4__ServiceException(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons4__ServiceException(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons4__PolicyException
#define SOAP_TYPE_PointerTons4__PolicyException (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons4__PolicyException(struct soap*, struct ns4__PolicyException *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons4__PolicyException(struct soap*, const char *, int, struct ns4__PolicyException *const*, const char *);
SOAP_FMAC3 struct ns4__PolicyException ** SOAP_FMAC4 soap_in_PointerTons4__PolicyException(struct soap*, const char*, struct ns4__PolicyException **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons4__PolicyException(struct soap*, struct ns4__PolicyException *const*, const char*, const char*);

#ifndef soap_write_PointerTons4__PolicyException
#define soap_write_PointerTons4__PolicyException(soap, data) ( soap_serialize_PointerTons4__PolicyException(soap, data), soap_begin_send(soap) || soap_put_PointerTons4__PolicyException(soap, data, "ns4:PolicyException", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns4__PolicyException ** SOAP_FMAC4 soap_get_PointerTons4__PolicyException(struct soap*, struct ns4__PolicyException **, const char*, const char*);

#ifndef soap_read_PointerTons4__PolicyException
#define soap_read_PointerTons4__PolicyException(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons4__PolicyException(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons4__RequestSOAPHeader
#define SOAP_TYPE_PointerTons4__RequestSOAPHeader (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons4__RequestSOAPHeader(struct soap*, struct ns4__RequestSOAPHeader *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons4__RequestSOAPHeader(struct soap*, const char *, int, struct ns4__RequestSOAPHeader *const*, const char *);
SOAP_FMAC3 struct ns4__RequestSOAPHeader ** SOAP_FMAC4 soap_in_PointerTons4__RequestSOAPHeader(struct soap*, const char*, struct ns4__RequestSOAPHeader **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons4__RequestSOAPHeader(struct soap*, struct ns4__RequestSOAPHeader *const*, const char*, const char*);

#ifndef soap_write_PointerTons4__RequestSOAPHeader
#define soap_write_PointerTons4__RequestSOAPHeader(soap, data) ( soap_serialize_PointerTons4__RequestSOAPHeader(soap, data), soap_begin_send(soap) || soap_put_PointerTons4__RequestSOAPHeader(soap, data, "ns4:RequestSOAPHeader", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns4__RequestSOAPHeader ** SOAP_FMAC4 soap_get_PointerTons4__RequestSOAPHeader(struct soap*, struct ns4__RequestSOAPHeader **, const char*, const char*);

#ifndef soap_read_PointerTons4__RequestSOAPHeader
#define soap_read_PointerTons4__RequestSOAPHeader(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons4__RequestSOAPHeader(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTostring
#define SOAP_TYPE_PointerTostring (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostring(struct soap*, char **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostring(struct soap*, const char *, int, char **const*, const char *);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_in_PointerTostring(struct soap*, const char*, char ***, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostring(struct soap*, char **const*, const char*, const char*);

#ifndef soap_write_PointerTostring
#define soap_write_PointerTostring(soap, data) ( soap_serialize_PointerTostring(soap, data), soap_begin_send(soap) || soap_put_PointerTostring(soap, data, "byte", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 char *** SOAP_FMAC4 soap_get_PointerTostring(struct soap*, char ***, const char*, const char*);

#ifndef soap_read_PointerTostring
#define soap_read_PointerTostring(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTostring(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerToxsd__boolean
#define SOAP_TYPE_PointerToxsd__boolean (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToxsd__boolean(struct soap*, enum xsd__boolean *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToxsd__boolean(struct soap*, const char *, int, enum xsd__boolean *const*, const char *);
SOAP_FMAC3 enum xsd__boolean ** SOAP_FMAC4 soap_in_PointerToxsd__boolean(struct soap*, const char*, enum xsd__boolean **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToxsd__boolean(struct soap*, enum xsd__boolean *const*, const char*, const char*);

#ifndef soap_write_PointerToxsd__boolean
#define soap_write_PointerToxsd__boolean(soap, data) ( soap_serialize_PointerToxsd__boolean(soap, data), soap_begin_send(soap) || soap_put_PointerToxsd__boolean(soap, data, "xsd:boolean", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 enum xsd__boolean ** SOAP_FMAC4 soap_get_PointerToxsd__boolean(struct soap*, enum xsd__boolean **, const char*, const char*);

#ifndef soap_read_PointerToxsd__boolean
#define soap_read_PointerToxsd__boolean(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToxsd__boolean(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons4__EndReason
#define SOAP_TYPE_PointerTons4__EndReason (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons4__EndReason(struct soap*, enum ns4__EndReason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons4__EndReason(struct soap*, const char *, int, enum ns4__EndReason *const*, const char *);
SOAP_FMAC3 enum ns4__EndReason ** SOAP_FMAC4 soap_in_PointerTons4__EndReason(struct soap*, const char*, enum ns4__EndReason **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons4__EndReason(struct soap*, enum ns4__EndReason *const*, const char*, const char*);

#ifndef soap_write_PointerTons4__EndReason
#define soap_write_PointerTons4__EndReason(soap, data) ( soap_serialize_PointerTons4__EndReason(soap, data), soap_begin_send(soap) || soap_put_PointerTons4__EndReason(soap, data, "ns4:EndReason", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 enum ns4__EndReason ** SOAP_FMAC4 soap_get_PointerTons4__EndReason(struct soap*, enum ns4__EndReason **, const char*, const char*);

#ifndef soap_read_PointerTons4__EndReason
#define soap_read_PointerTons4__EndReason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons4__EndReason(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons5__DeliveryInformation
#define SOAP_TYPE_PointerTons5__DeliveryInformation (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons5__DeliveryInformation(struct soap*, struct ns5__DeliveryInformation *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons5__DeliveryInformation(struct soap*, const char *, int, struct ns5__DeliveryInformation *const*, const char *);
SOAP_FMAC3 struct ns5__DeliveryInformation ** SOAP_FMAC4 soap_in_PointerTons5__DeliveryInformation(struct soap*, const char*, struct ns5__DeliveryInformation **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons5__DeliveryInformation(struct soap*, struct ns5__DeliveryInformation *const*, const char*, const char*);

#ifndef soap_write_PointerTons5__DeliveryInformation
#define soap_write_PointerTons5__DeliveryInformation(soap, data) ( soap_serialize_PointerTons5__DeliveryInformation(soap, data), soap_begin_send(soap) || soap_put_PointerTons5__DeliveryInformation(soap, data, "ns5:DeliveryInformation", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns5__DeliveryInformation ** SOAP_FMAC4 soap_get_PointerTons5__DeliveryInformation(struct soap*, struct ns5__DeliveryInformation **, const char*, const char*);

#ifndef soap_read_PointerTons5__DeliveryInformation
#define soap_read_PointerTons5__DeliveryInformation(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons5__DeliveryInformation(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons4__SimpleReference
#define SOAP_TYPE_PointerTons4__SimpleReference (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons4__SimpleReference(struct soap*, struct ns4__SimpleReference *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons4__SimpleReference(struct soap*, const char *, int, struct ns4__SimpleReference *const*, const char *);
SOAP_FMAC3 struct ns4__SimpleReference ** SOAP_FMAC4 soap_in_PointerTons4__SimpleReference(struct soap*, const char*, struct ns4__SimpleReference **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons4__SimpleReference(struct soap*, struct ns4__SimpleReference *const*, const char*, const char*);

#ifndef soap_write_PointerTons4__SimpleReference
#define soap_write_PointerTons4__SimpleReference(soap, data) ( soap_serialize_PointerTons4__SimpleReference(soap, data), soap_begin_send(soap) || soap_put_PointerTons4__SimpleReference(soap, data, "ns4:SimpleReference", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns4__SimpleReference ** SOAP_FMAC4 soap_get_PointerTons4__SimpleReference(struct soap*, struct ns4__SimpleReference **, const char*, const char*);

#ifndef soap_read_PointerTons4__SimpleReference
#define soap_read_PointerTons4__SimpleReference(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons4__SimpleReference(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons4__ChargingInformation
#define SOAP_TYPE_PointerTons4__ChargingInformation (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons4__ChargingInformation(struct soap*, struct ns4__ChargingInformation *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons4__ChargingInformation(struct soap*, const char *, int, struct ns4__ChargingInformation *const*, const char *);
SOAP_FMAC3 struct ns4__ChargingInformation ** SOAP_FMAC4 soap_in_PointerTons4__ChargingInformation(struct soap*, const char*, struct ns4__ChargingInformation **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons4__ChargingInformation(struct soap*, struct ns4__ChargingInformation *const*, const char*, const char*);

#ifndef soap_write_PointerTons4__ChargingInformation
#define soap_write_PointerTons4__ChargingInformation(soap, data) ( soap_serialize_PointerTons4__ChargingInformation(soap, data), soap_begin_send(soap) || soap_put_PointerTons4__ChargingInformation(soap, data, "ns4:ChargingInformation", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns4__ChargingInformation ** SOAP_FMAC4 soap_get_PointerTons4__ChargingInformation(struct soap*, struct ns4__ChargingInformation **, const char*, const char*);

#ifndef soap_read_PointerTons4__ChargingInformation
#define soap_read_PointerTons4__ChargingInformation(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons4__ChargingInformation(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerToxsd__anyURI
#define SOAP_TYPE_PointerToxsd__anyURI (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToxsd__anyURI(struct soap*, char **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToxsd__anyURI(struct soap*, const char *, int, char **const*, const char *);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_in_PointerToxsd__anyURI(struct soap*, const char*, char ***, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToxsd__anyURI(struct soap*, char **const*, const char*, const char*);

#ifndef soap_write_PointerToxsd__anyURI
#define soap_write_PointerToxsd__anyURI(soap, data) ( soap_serialize_PointerToxsd__anyURI(soap, data), soap_begin_send(soap) || soap_put_PointerToxsd__anyURI(soap, data, "byte", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 char *** SOAP_FMAC4 soap_get_PointerToxsd__anyURI(struct soap*, char ***, const char*, const char*);

#ifndef soap_read_PointerToxsd__anyURI
#define soap_read_PointerToxsd__anyURI(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToxsd__anyURI(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_xsd__decimal
#define SOAP_TYPE_xsd__decimal (13)
#endif

#define soap_default_xsd__decimal(soap, a) soap_default_string(soap, a)

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__decimal(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__decimal(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__decimal(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__decimal(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write_xsd__decimal
#define soap_write_xsd__decimal(soap, data) ( soap_serialize_xsd__decimal(soap, data), soap_begin_send(soap) || soap_put_xsd__decimal(soap, data, "byte", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__decimal(struct soap*, char **, const char*, const char*);

#ifndef soap_read_xsd__decimal
#define soap_read_xsd__decimal(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__decimal(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_xsd__anyURI
#define SOAP_TYPE_xsd__anyURI (12)
#endif

#define soap_default_xsd__anyURI(soap, a) soap_default_string(soap, a)

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__anyURI(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__anyURI(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__anyURI(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__anyURI(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write_xsd__anyURI
#define soap_write_xsd__anyURI(soap, data) ( soap_serialize_xsd__anyURI(soap, data), soap_begin_send(soap) || soap_put_xsd__anyURI(soap, data, "byte", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__anyURI(struct soap*, char **, const char*, const char*);

#ifndef soap_read_xsd__anyURI
#define soap_read_xsd__anyURI(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__anyURI(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTounsignedByte
#define SOAP_TYPE_PointerTounsignedByte (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTounsignedByte(struct soap*, unsigned char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTounsignedByte(struct soap*, const char *, int, unsigned char *const*, const char *);
SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_in_PointerTounsignedByte(struct soap*, const char*, unsigned char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTounsignedByte(struct soap*, unsigned char *const*, const char*, const char*);

#ifndef soap_write_PointerTounsignedByte
#define soap_write_PointerTounsignedByte(soap, data) ( soap_serialize_PointerTounsignedByte(soap, data), soap_begin_send(soap) || soap_put_PointerTounsignedByte(soap, data, "unsignedByte", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_get_PointerTounsignedByte(struct soap*, unsigned char **, const char*, const char*);

#ifndef soap_read_PointerTounsignedByte
#define soap_read_PointerTounsignedByte(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTounsignedByte(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_serialize__QName(soap, data), soap_begin_send(soap) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_serialize_string(soap, data), soap_begin_send(soap) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifdef __cplusplus
}
#endif

#endif

/* End of soapH.h */
