/* soapStub.h
   Generated by gSOAP 2.8.15 from ctcc_sms_send_service_2_1.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapStub_H
#define soapStub_H
#define SOAP_NAMESPACE_OF_ns2	"http://www.chinatelecom.com.cn/schema/ctcc/sms/send/v2_1/local"
#define SOAP_NAMESPACE_OF_ns3	""
#define SOAP_NAMESPACE_OF_ns4	"http://www.chinatelecom.com.cn/schema/ctcc/common/v2_1"
#define SOAP_NAMESPACE_OF_ns5	"http://www.chinatelecom.com.cn/schema/ctcc/sms/v2_1"
#include "stdsoap2.h"
#if GSOAP_VERSION != 20815
# error "GSOAP VERSION MISMATCH IN GENERATED CODE: PLEASE REINSTALL PACKAGE"
#endif

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (11)
/* xsd:boolean */
enum xsd__boolean { xsd__boolean__false_ = 0, xsd__boolean__true_ = 1 };
#endif

#ifndef SOAP_TYPE_ns4__DeliveryConfirmStatus
#define SOAP_TYPE_ns4__DeliveryConfirmStatus (14)
/* ns4:DeliveryConfirmStatus */
enum ns4__DeliveryConfirmStatus { ns4__DeliveryConfirmStatus__Success = 0, ns4__DeliveryConfirmStatus__Fail = 1 };
#endif

#ifndef SOAP_TYPE_ns4__EndReason
#define SOAP_TYPE_ns4__EndReason (15)
/* ns4:EndReason */
enum ns4__EndReason { ns4__EndReason__0 = 0, ns4__EndReason___x002d1 = -1, ns4__EndReason__1 = 1, ns4__EndReason__2 = 2 };
#endif

#ifndef SOAP_TYPE_ns4__TimeMetrics
#define SOAP_TYPE_ns4__TimeMetrics (16)
/* ns4:TimeMetrics */
enum ns4__TimeMetrics { ns4__TimeMetrics__Millisecond = 0, ns4__TimeMetrics__Second = 1, ns4__TimeMetrics__Minute = 2, ns4__TimeMetrics__Hour = 3, ns4__TimeMetrics__Day = 4, ns4__TimeMetrics__Week = 5, ns4__TimeMetrics__Month = 6, ns4__TimeMetrics__Year = 7 };
#endif

#ifndef SOAP_TYPE_ns5__DeliveryStatus
#define SOAP_TYPE_ns5__DeliveryStatus (17)
/* ns5:DeliveryStatus */
enum ns5__DeliveryStatus { ns5__DeliveryStatus__DeliveredToNetwork = 0, ns5__DeliveryStatus__DeliveryUncertain = 1, ns5__DeliveryStatus__DeliveryImpossible = 2, ns5__DeliveryStatus__MessageWaiting = 3, ns5__DeliveryStatus__DeliveredToTerminal = 4, ns5__DeliveryStatus__DeliveryNotificationNotSupported = 5, ns5__DeliveryStatus__AuthPriceFailed = 6 };
#endif

#ifndef SOAP_TYPE_ns5__SmsFormat
#define SOAP_TYPE_ns5__SmsFormat (18)
/* ns5:SmsFormat */
enum ns5__SmsFormat { ns5__SmsFormat__Ems = 0, ns5__SmsFormat__SmartMessaging = 1 };
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_xsd__base64Binary
#define SOAP_TYPE_xsd__base64Binary (7)
/* Base64 schema type: */
struct xsd__base64Binary
{
	unsigned char *__ptr;
	int __size;
	char *id;	/* optional element of type xsd:string */
	char *type;	/* optional element of type xsd:string */
	char *options;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns2__sendSms
#define SOAP_TYPE_ns2__sendSms (19)
/* ns2:sendSms */
struct ns2__sendSms
{
	int __sizeaddresses;	/* sequence of elements <addresses> */
	char **addresses;	/* required element of type xsd:anyURI */
	char *senderName;	/* optional element of type xsd:string */
	struct ns4__ChargingInformation *charging;	/* optional element of type ns4:ChargingInformation */
	char *message;	/* required element of type xsd:string */
	struct ns4__SimpleReference *receiptRequest;	/* optional element of type ns4:SimpleReference */
};
#endif

#ifndef SOAP_TYPE_ns2__sendSmsResponse
#define SOAP_TYPE_ns2__sendSmsResponse (25)
/* ns2:sendSmsResponse */
struct ns2__sendSmsResponse
{
	char *result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns2__sendSmsLogo
#define SOAP_TYPE_ns2__sendSmsLogo (26)
/* ns2:sendSmsLogo */
struct ns2__sendSmsLogo
{
	int __sizeaddresses;	/* sequence of elements <addresses> */
	char **addresses;	/* required element of type xsd:anyURI */
	char *senderName;	/* optional element of type xsd:string */
	struct ns4__ChargingInformation *charging;	/* optional element of type ns4:ChargingInformation */
	struct xsd__base64Binary image;	/* required element of type xsd:base64Binary */
	enum ns5__SmsFormat smsFormat;	/* required element of type ns5:SmsFormat */
	struct ns4__SimpleReference *receiptRequest;	/* optional element of type ns4:SimpleReference */
};
#endif

#ifndef SOAP_TYPE_ns2__sendSmsLogoResponse
#define SOAP_TYPE_ns2__sendSmsLogoResponse (27)
/* ns2:sendSmsLogoResponse */
struct ns2__sendSmsLogoResponse
{
	char *result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns2__sendSmsRingtone
#define SOAP_TYPE_ns2__sendSmsRingtone (28)
/* ns2:sendSmsRingtone */
struct ns2__sendSmsRingtone
{
	int __sizeaddresses;	/* sequence of elements <addresses> */
	char **addresses;	/* required element of type xsd:anyURI */
	char *senderName;	/* optional element of type xsd:string */
	struct ns4__ChargingInformation *charging;	/* optional element of type ns4:ChargingInformation */
	char *ringtone;	/* required element of type xsd:string */
	enum ns5__SmsFormat smsFormat;	/* required element of type ns5:SmsFormat */
	struct ns4__SimpleReference *receiptRequest;	/* optional element of type ns4:SimpleReference */
};
#endif

#ifndef SOAP_TYPE_ns2__sendSmsRingtoneResponse
#define SOAP_TYPE_ns2__sendSmsRingtoneResponse (29)
/* ns2:sendSmsRingtoneResponse */
struct ns2__sendSmsRingtoneResponse
{
	char *result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns2__getSmsDeliveryStatus
#define SOAP_TYPE_ns2__getSmsDeliveryStatus (30)
/* ns2:getSmsDeliveryStatus */
struct ns2__getSmsDeliveryStatus
{
	char *requestIdentifier;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns2__getSmsDeliveryStatusResponse
#define SOAP_TYPE_ns2__getSmsDeliveryStatusResponse (31)
/* ns2:getSmsDeliveryStatusResponse */
struct ns2__getSmsDeliveryStatusResponse
{
	int __sizeresult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* sequence of elements <result> */
	struct ns5__DeliveryInformation *result;	/* optional element of type ns5:DeliveryInformation */
};
#endif

#ifndef SOAP_TYPE_ns4__RequestSOAPHeader
#define SOAP_TYPE_ns4__RequestSOAPHeader (34)
/* ns4:RequestSOAPHeader */
struct ns4__RequestSOAPHeader
{
	char *spId;	/* required element of type xsd:string */
	char *spPassword;	/* required element of type xsd:string */
	char *timeStamp;	/* required element of type xsd:string */
	char *productId;	/* required element of type xsd:string */
	char *SAN;	/* optional element of type xsd:string */
	char *transactionId;	/* optional element of type xsd:string */
	enum ns4__EndReason *transEnd;	/* optional element of type ns4:EndReason */
	char *linkId;	/* optional element of type xsd:string */
	char *OA;	/* optional element of type xsd:anyURI */
	char *FA;	/* optional element of type xsd:anyURI */
	enum xsd__boolean *multicastMessaging;	/* optional element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_ns4__NotifySOAPHeader
#define SOAP_TYPE_ns4__NotifySOAPHeader (37)
/* ns4:NotifySOAPHeader */
struct ns4__NotifySOAPHeader
{
	char *spRevId;	/* optional element of type xsd:string */
	char *spRevpassword;	/* optional element of type xsd:string */
	char *spId;	/* required element of type xsd:string */
	char *SAN;	/* optional element of type xsd:string */
	char *transactionId;	/* optional element of type xsd:string */
	char *linkId;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns4__TimeMetric
#define SOAP_TYPE_ns4__TimeMetric (38)
/* ns4:TimeMetric */
struct ns4__TimeMetric
{
	enum ns4__TimeMetrics metric;	/* required element of type ns4:TimeMetrics */
	int units;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns4__ChargingInformation
#define SOAP_TYPE_ns4__ChargingInformation (21)
/* ns4:ChargingInformation */
struct ns4__ChargingInformation
{
	char *description;	/* required element of type xsd:string */
	char *currency;	/* optional element of type xsd:string */
	char *amount;	/* optional element of type xsd:decimal */
	char *code;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns4__SimpleReference
#define SOAP_TYPE_ns4__SimpleReference (23)
/* ns4:SimpleReference */
struct ns4__SimpleReference
{
	char *endpoint;	/* required element of type xsd:anyURI */
	char *interfaceName;	/* required element of type xsd:string */
	char *correlator;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns4__ServiceError
#define SOAP_TYPE_ns4__ServiceError (39)
/* ns4:ServiceError */
struct ns4__ServiceError
{
	char *messageId;	/* required element of type xsd:string */
	char *text;	/* required element of type xsd:string */
	int __sizevariables;	/* sequence of elements <variables> */
	char **variables;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns4__ServiceException
#define SOAP_TYPE_ns4__ServiceException (41)
/* ns4:ServiceException */
struct ns4__ServiceException
{
	char *messageId;	/* required element of type xsd:string */
	char *text;	/* required element of type xsd:string */
	int __sizevariables;	/* sequence of elements <variables> */
	char **variables;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns4__PolicyException
#define SOAP_TYPE_ns4__PolicyException (42)
/* ns4:PolicyException */
struct ns4__PolicyException
{
	char *messageId;	/* required element of type xsd:string */
	char *text;	/* required element of type xsd:string */
	int __sizevariables;	/* sequence of elements <variables> */
	char **variables;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns5__DeliveryInformation
#define SOAP_TYPE_ns5__DeliveryInformation (32)
/* ns5:DeliveryInformation */
struct ns5__DeliveryInformation
{
	char *address;	/* required element of type xsd:anyURI */
	enum ns5__DeliveryStatus deliveryStatus;	/* required element of type ns5:DeliveryStatus */
};
#endif

#ifndef SOAP_TYPE_ns5__SmsMessage
#define SOAP_TYPE_ns5__SmsMessage (43)
/* ns5:SmsMessage */
struct ns5__SmsMessage
{
	char *message;	/* required element of type xsd:string */
	char *senderAddress;	/* required element of type xsd:anyURI */
	char *smsServiceActivationNumber;	/* required element of type xsd:anyURI */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (44)
/* SOAP Header: */
struct SOAP_ENV__Header
{
	struct ns4__RequestSOAPHeader *ns4__RequestSOAPHeader;	/* mustUnderstand */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (46)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	char *__any;
	struct ns4__PolicyException *ns4__PolicyException;	/* optional element of type ns4:PolicyException */
	struct ns4__ServiceException *ns4__ServiceException;	/* optional element of type ns4:ServiceException */
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
};
#endif

#endif

#ifndef SOAP_TYPE___ns1__sendSms
#define SOAP_TYPE___ns1__sendSms (54)
/* Operation wrapper: */
struct __ns1__sendSms
{
	struct ns2__sendSms *ns2__sendSms;	/* optional element of type ns2:sendSms */
};
#endif

#ifndef SOAP_TYPE___ns1__sendSmsLogo
#define SOAP_TYPE___ns1__sendSmsLogo (58)
/* Operation wrapper: */
struct __ns1__sendSmsLogo
{
	struct ns2__sendSmsLogo *ns2__sendSmsLogo;	/* optional element of type ns2:sendSmsLogo */
};
#endif

#ifndef SOAP_TYPE___ns1__sendSmsRingtone
#define SOAP_TYPE___ns1__sendSmsRingtone (62)
/* Operation wrapper: */
struct __ns1__sendSmsRingtone
{
	struct ns2__sendSmsRingtone *ns2__sendSmsRingtone;	/* optional element of type ns2:sendSmsRingtone */
};
#endif

#ifndef SOAP_TYPE___ns1__getSmsDeliveryStatus
#define SOAP_TYPE___ns1__getSmsDeliveryStatus (66)
/* Operation wrapper: */
struct __ns1__getSmsDeliveryStatus
{
	struct ns2__getSmsDeliveryStatus *ns2__getSmsDeliveryStatus;	/* optional element of type ns2:getSmsDeliveryStatus */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (67)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (69)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (70)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif

#ifndef SOAP_TYPE_xsd__anyURI
#define SOAP_TYPE_xsd__anyURI (12)
typedef char *xsd__anyURI;
#endif

#ifndef SOAP_TYPE_xsd__decimal
#define SOAP_TYPE_xsd__decimal (13)
typedef char *xsd__decimal;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 __ns1__sendSms(struct soap*, struct ns2__sendSms *ns2__sendSms, struct ns2__sendSmsResponse *ns2__sendSmsResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns1__sendSmsLogo(struct soap*, struct ns2__sendSmsLogo *ns2__sendSmsLogo, struct ns2__sendSmsLogoResponse *ns2__sendSmsLogoResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns1__sendSmsRingtone(struct soap*, struct ns2__sendSmsRingtone *ns2__sendSmsRingtone, struct ns2__sendSmsRingtoneResponse *ns2__sendSmsRingtoneResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns1__getSmsDeliveryStatus(struct soap*, struct ns2__getSmsDeliveryStatus *ns2__getSmsDeliveryStatus, struct ns2__getSmsDeliveryStatusResponse *ns2__getSmsDeliveryStatusResponse);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__sendSms(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__sendSmsLogo(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__sendSmsRingtone(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__getSmsDeliveryStatus(struct soap*);

/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__sendSms(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns2__sendSms *ns2__sendSms, struct ns2__sendSmsResponse *ns2__sendSmsResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__sendSmsLogo(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns2__sendSmsLogo *ns2__sendSmsLogo, struct ns2__sendSmsLogoResponse *ns2__sendSmsLogoResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__sendSmsRingtone(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns2__sendSmsRingtone *ns2__sendSmsRingtone, struct ns2__sendSmsRingtoneResponse *ns2__sendSmsRingtoneResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getSmsDeliveryStatus(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns2__getSmsDeliveryStatus *ns2__getSmsDeliveryStatus, struct ns2__getSmsDeliveryStatusResponse *ns2__getSmsDeliveryStatusResponse);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
