/* soapH.h
   Generated by gSOAP 2.8.15 from SmsNotificationService.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifdef __cplusplus
extern "C" {
#endif
#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultcode(struct soap *soap);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_serialize_byte(soap, data), soap_begin_send(soap) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_serialize_int(soap, data), soap_begin_send(soap) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_serialize_SOAP_ENV__Fault(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_serialize_SOAP_ENV__Reason(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_serialize_SOAP_ENV__Detail(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_serialize_SOAP_ENV__Code(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_serialize_SOAP_ENV__Header(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef SOAP_TYPE_ns1__notifySmsDeliveryReceipt
#define SOAP_TYPE_ns1__notifySmsDeliveryReceipt (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__notifySmsDeliveryReceipt(struct soap*, struct ns1__notifySmsDeliveryReceipt *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__notifySmsDeliveryReceipt(struct soap*, const struct ns1__notifySmsDeliveryReceipt *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__notifySmsDeliveryReceipt(struct soap*, const char*, int, const struct ns1__notifySmsDeliveryReceipt *, const char*);
SOAP_FMAC3 struct ns1__notifySmsDeliveryReceipt * SOAP_FMAC4 soap_in_ns1__notifySmsDeliveryReceipt(struct soap*, const char*, struct ns1__notifySmsDeliveryReceipt *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__notifySmsDeliveryReceipt(struct soap*, const struct ns1__notifySmsDeliveryReceipt *, const char*, const char*);

#ifndef soap_write_ns1__notifySmsDeliveryReceipt
#define soap_write_ns1__notifySmsDeliveryReceipt(soap, data) ( soap_serialize_ns1__notifySmsDeliveryReceipt(soap, data), soap_begin_send(soap) || soap_put_ns1__notifySmsDeliveryReceipt(soap, data, "ns1:notifySmsDeliveryReceipt", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns1__notifySmsDeliveryReceipt * SOAP_FMAC4 soap_get_ns1__notifySmsDeliveryReceipt(struct soap*, struct ns1__notifySmsDeliveryReceipt *, const char*, const char*);

#ifndef soap_read_ns1__notifySmsDeliveryReceipt
#define soap_read_ns1__notifySmsDeliveryReceipt(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__notifySmsDeliveryReceipt(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns1__notifySmsDeliveryReceiptResponse
#define SOAP_TYPE_ns1__notifySmsDeliveryReceiptResponse (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__notifySmsDeliveryReceiptResponse(struct soap*, struct ns1__notifySmsDeliveryReceiptResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__notifySmsDeliveryReceiptResponse(struct soap*, const struct ns1__notifySmsDeliveryReceiptResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__notifySmsDeliveryReceiptResponse(struct soap*, const char*, int, const struct ns1__notifySmsDeliveryReceiptResponse *, const char*);
SOAP_FMAC3 struct ns1__notifySmsDeliveryReceiptResponse * SOAP_FMAC4 soap_in_ns1__notifySmsDeliveryReceiptResponse(struct soap*, const char*, struct ns1__notifySmsDeliveryReceiptResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__notifySmsDeliveryReceiptResponse(struct soap*, const struct ns1__notifySmsDeliveryReceiptResponse *, const char*, const char*);

#ifndef soap_write_ns1__notifySmsDeliveryReceiptResponse
#define soap_write_ns1__notifySmsDeliveryReceiptResponse(soap, data) ( soap_serialize_ns1__notifySmsDeliveryReceiptResponse(soap, data), soap_begin_send(soap) || soap_put_ns1__notifySmsDeliveryReceiptResponse(soap, data, "ns1:notifySmsDeliveryReceiptResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns1__notifySmsDeliveryReceiptResponse * SOAP_FMAC4 soap_get_ns1__notifySmsDeliveryReceiptResponse(struct soap*, struct ns1__notifySmsDeliveryReceiptResponse *, const char*, const char*);

#ifndef soap_read_ns1__notifySmsDeliveryReceiptResponse
#define soap_read_ns1__notifySmsDeliveryReceiptResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__notifySmsDeliveryReceiptResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns1__notifySmsReception
#define SOAP_TYPE_ns1__notifySmsReception (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__notifySmsReception(struct soap*, struct ns1__notifySmsReception *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__notifySmsReception(struct soap*, const struct ns1__notifySmsReception *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__notifySmsReception(struct soap*, const char*, int, const struct ns1__notifySmsReception *, const char*);
SOAP_FMAC3 struct ns1__notifySmsReception * SOAP_FMAC4 soap_in_ns1__notifySmsReception(struct soap*, const char*, struct ns1__notifySmsReception *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__notifySmsReception(struct soap*, const struct ns1__notifySmsReception *, const char*, const char*);

#ifndef soap_write_ns1__notifySmsReception
#define soap_write_ns1__notifySmsReception(soap, data) ( soap_serialize_ns1__notifySmsReception(soap, data), soap_begin_send(soap) || soap_put_ns1__notifySmsReception(soap, data, "ns1:notifySmsReception", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns1__notifySmsReception * SOAP_FMAC4 soap_get_ns1__notifySmsReception(struct soap*, struct ns1__notifySmsReception *, const char*, const char*);

#ifndef soap_read_ns1__notifySmsReception
#define soap_read_ns1__notifySmsReception(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__notifySmsReception(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns1__notifySmsReceptionResponse
#define SOAP_TYPE_ns1__notifySmsReceptionResponse (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__notifySmsReceptionResponse(struct soap*, struct ns1__notifySmsReceptionResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__notifySmsReceptionResponse(struct soap*, const struct ns1__notifySmsReceptionResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__notifySmsReceptionResponse(struct soap*, const char*, int, const struct ns1__notifySmsReceptionResponse *, const char*);
SOAP_FMAC3 struct ns1__notifySmsReceptionResponse * SOAP_FMAC4 soap_in_ns1__notifySmsReceptionResponse(struct soap*, const char*, struct ns1__notifySmsReceptionResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__notifySmsReceptionResponse(struct soap*, const struct ns1__notifySmsReceptionResponse *, const char*, const char*);

#ifndef soap_write_ns1__notifySmsReceptionResponse
#define soap_write_ns1__notifySmsReceptionResponse(soap, data) ( soap_serialize_ns1__notifySmsReceptionResponse(soap, data), soap_begin_send(soap) || soap_put_ns1__notifySmsReceptionResponse(soap, data, "ns1:notifySmsReceptionResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns1__notifySmsReceptionResponse * SOAP_FMAC4 soap_get_ns1__notifySmsReceptionResponse(struct soap*, struct ns1__notifySmsReceptionResponse *, const char*, const char*);

#ifndef soap_read_ns1__notifySmsReceptionResponse
#define soap_read_ns1__notifySmsReceptionResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__notifySmsReceptionResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns1__DeliveryInformation
#define SOAP_TYPE_ns1__DeliveryInformation (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__DeliveryInformation(struct soap*, struct ns1__DeliveryInformation *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__DeliveryInformation(struct soap*, const struct ns1__DeliveryInformation *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__DeliveryInformation(struct soap*, const char*, int, const struct ns1__DeliveryInformation *, const char*);
SOAP_FMAC3 struct ns1__DeliveryInformation * SOAP_FMAC4 soap_in_ns1__DeliveryInformation(struct soap*, const char*, struct ns1__DeliveryInformation *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__DeliveryInformation(struct soap*, const struct ns1__DeliveryInformation *, const char*, const char*);

#ifndef soap_write_ns1__DeliveryInformation
#define soap_write_ns1__DeliveryInformation(soap, data) ( soap_serialize_ns1__DeliveryInformation(soap, data), soap_begin_send(soap) || soap_put_ns1__DeliveryInformation(soap, data, "ns1:DeliveryInformation", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns1__DeliveryInformation * SOAP_FMAC4 soap_get_ns1__DeliveryInformation(struct soap*, struct ns1__DeliveryInformation *, const char*, const char*);

#ifndef soap_read_ns1__DeliveryInformation
#define soap_read_ns1__DeliveryInformation(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__DeliveryInformation(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns1__SmsMessage
#define SOAP_TYPE_ns1__SmsMessage (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__SmsMessage(struct soap*, struct ns1__SmsMessage *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__SmsMessage(struct soap*, const struct ns1__SmsMessage *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__SmsMessage(struct soap*, const char*, int, const struct ns1__SmsMessage *, const char*);
SOAP_FMAC3 struct ns1__SmsMessage * SOAP_FMAC4 soap_in_ns1__SmsMessage(struct soap*, const char*, struct ns1__SmsMessage *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__SmsMessage(struct soap*, const struct ns1__SmsMessage *, const char*, const char*);

#ifndef soap_write_ns1__SmsMessage
#define soap_write_ns1__SmsMessage(soap, data) ( soap_serialize_ns1__SmsMessage(soap, data), soap_begin_send(soap) || soap_put_ns1__SmsMessage(soap, data, "ns1:SmsMessage", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns1__SmsMessage * SOAP_FMAC4 soap_get_ns1__SmsMessage(struct soap*, struct ns1__SmsMessage *, const char*, const char*);

#ifndef soap_read_ns1__SmsMessage
#define soap_read_ns1__SmsMessage(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__SmsMessage(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_serialize_PointerToSOAP_ENV__Reason(soap, data), soap_begin_send(soap) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_serialize_PointerToSOAP_ENV__Detail(soap, data), soap_begin_send(soap) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_serialize_PointerToSOAP_ENV__Code(soap, data), soap_begin_send(soap) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef SOAP_TYPE_PointerTons1__notifySmsDeliveryReceiptResponse
#define SOAP_TYPE_PointerTons1__notifySmsDeliveryReceiptResponse (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__notifySmsDeliveryReceiptResponse(struct soap*, struct ns1__notifySmsDeliveryReceiptResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__notifySmsDeliveryReceiptResponse(struct soap*, const char *, int, struct ns1__notifySmsDeliveryReceiptResponse *const*, const char *);
SOAP_FMAC3 struct ns1__notifySmsDeliveryReceiptResponse ** SOAP_FMAC4 soap_in_PointerTons1__notifySmsDeliveryReceiptResponse(struct soap*, const char*, struct ns1__notifySmsDeliveryReceiptResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__notifySmsDeliveryReceiptResponse(struct soap*, struct ns1__notifySmsDeliveryReceiptResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTons1__notifySmsDeliveryReceiptResponse
#define soap_write_PointerTons1__notifySmsDeliveryReceiptResponse(soap, data) ( soap_serialize_PointerTons1__notifySmsDeliveryReceiptResponse(soap, data), soap_begin_send(soap) || soap_put_PointerTons1__notifySmsDeliveryReceiptResponse(soap, data, "ns1:notifySmsDeliveryReceiptResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns1__notifySmsDeliveryReceiptResponse ** SOAP_FMAC4 soap_get_PointerTons1__notifySmsDeliveryReceiptResponse(struct soap*, struct ns1__notifySmsDeliveryReceiptResponse **, const char*, const char*);

#ifndef soap_read_PointerTons1__notifySmsDeliveryReceiptResponse
#define soap_read_PointerTons1__notifySmsDeliveryReceiptResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__notifySmsDeliveryReceiptResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons1__DeliveryInformation
#define SOAP_TYPE_PointerTons1__DeliveryInformation (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__DeliveryInformation(struct soap*, struct ns1__DeliveryInformation *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__DeliveryInformation(struct soap*, const char *, int, struct ns1__DeliveryInformation *const*, const char *);
SOAP_FMAC3 struct ns1__DeliveryInformation ** SOAP_FMAC4 soap_in_PointerTons1__DeliveryInformation(struct soap*, const char*, struct ns1__DeliveryInformation **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__DeliveryInformation(struct soap*, struct ns1__DeliveryInformation *const*, const char*, const char*);

#ifndef soap_write_PointerTons1__DeliveryInformation
#define soap_write_PointerTons1__DeliveryInformation(soap, data) ( soap_serialize_PointerTons1__DeliveryInformation(soap, data), soap_begin_send(soap) || soap_put_PointerTons1__DeliveryInformation(soap, data, "ns1:DeliveryInformation", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns1__DeliveryInformation ** SOAP_FMAC4 soap_get_PointerTons1__DeliveryInformation(struct soap*, struct ns1__DeliveryInformation **, const char*, const char*);

#ifndef soap_read_PointerTons1__DeliveryInformation
#define soap_read_PointerTons1__DeliveryInformation(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__DeliveryInformation(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons1__notifySmsReceptionResponse
#define SOAP_TYPE_PointerTons1__notifySmsReceptionResponse (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__notifySmsReceptionResponse(struct soap*, struct ns1__notifySmsReceptionResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__notifySmsReceptionResponse(struct soap*, const char *, int, struct ns1__notifySmsReceptionResponse *const*, const char *);
SOAP_FMAC3 struct ns1__notifySmsReceptionResponse ** SOAP_FMAC4 soap_in_PointerTons1__notifySmsReceptionResponse(struct soap*, const char*, struct ns1__notifySmsReceptionResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__notifySmsReceptionResponse(struct soap*, struct ns1__notifySmsReceptionResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTons1__notifySmsReceptionResponse
#define soap_write_PointerTons1__notifySmsReceptionResponse(soap, data) ( soap_serialize_PointerTons1__notifySmsReceptionResponse(soap, data), soap_begin_send(soap) || soap_put_PointerTons1__notifySmsReceptionResponse(soap, data, "ns1:notifySmsReceptionResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns1__notifySmsReceptionResponse ** SOAP_FMAC4 soap_get_PointerTons1__notifySmsReceptionResponse(struct soap*, struct ns1__notifySmsReceptionResponse **, const char*, const char*);

#ifndef soap_read_PointerTons1__notifySmsReceptionResponse
#define soap_read_PointerTons1__notifySmsReceptionResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__notifySmsReceptionResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons1__SmsMessage
#define SOAP_TYPE_PointerTons1__SmsMessage (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__SmsMessage(struct soap*, struct ns1__SmsMessage *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__SmsMessage(struct soap*, const char *, int, struct ns1__SmsMessage *const*, const char *);
SOAP_FMAC3 struct ns1__SmsMessage ** SOAP_FMAC4 soap_in_PointerTons1__SmsMessage(struct soap*, const char*, struct ns1__SmsMessage **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__SmsMessage(struct soap*, struct ns1__SmsMessage *const*, const char*, const char*);

#ifndef soap_write_PointerTons1__SmsMessage
#define soap_write_PointerTons1__SmsMessage(soap, data) ( soap_serialize_PointerTons1__SmsMessage(soap, data), soap_begin_send(soap) || soap_put_PointerTons1__SmsMessage(soap, data, "ns1:SmsMessage", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns1__SmsMessage ** SOAP_FMAC4 soap_get_PointerTons1__SmsMessage(struct soap*, struct ns1__SmsMessage **, const char*, const char*);

#ifndef soap_read_PointerTons1__SmsMessage
#define soap_read_PointerTons1__SmsMessage(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__SmsMessage(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_xsd__anyURI
#define SOAP_TYPE_xsd__anyURI (7)
#endif

#define soap_default_xsd__anyURI(soap, a) soap_default_string(soap, a)

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__anyURI(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__anyURI(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__anyURI(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__anyURI(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write_xsd__anyURI
#define soap_write_xsd__anyURI(soap, data) ( soap_serialize_xsd__anyURI(soap, data), soap_begin_send(soap) || soap_put_xsd__anyURI(soap, data, "byte", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__anyURI(struct soap*, char **, const char*, const char*);

#ifndef soap_read_xsd__anyURI
#define soap_read_xsd__anyURI(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__anyURI(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_serialize__QName(soap, data), soap_begin_send(soap) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_serialize_string(soap, data), soap_begin_send(soap) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifdef __cplusplus
}
#endif

#endif

/* End of soapH.h */
