/* SendSmsService.h
   Generated by wsdl2h 2.8.15 from SendSmsService.wsdl and typemap.dat
   2013-10-14 12:55:07 GMT

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS
   USE THE soapcpp2-GENERATED SOURCE CODE FILES FOR YOUR PROJECT BUILDS

   gSOAP XML Web services tools.
   Copyright (C) 2000-2013 Robert van Engelen, Genivia Inc. All Rights Reserved.
   Part of this software is released under one of the following licenses:
   GPL or Genivia's license for commercial use.
*/

/** @page page_notes Usage Notes

NOTE:

 - Run soapcpp2 on SendSmsService.h to generate the SOAP/XML processing logic.
   Use soapcpp2 -I to specify paths for #import
   To build with STL, 'stlvector.h' is imported from 'import' dir in package.
   Use soapcpp2 -j to generate improved proxy and server classes.
 - Use wsdl2h -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Use Doxygen (www.doxygen.org) on this file to generate documentation.
 - Use wsdl2h -R to generate REST operations.
 - Use wsdl2h -nname to use name as the base namespace prefix instead of 'ns'.
 - Use wsdl2h -Nname for service prefix and produce multiple service bindings
 - Use wsdl2h -d to enable DOM support for xsd:anyType.
 - Use wsdl2h -g to auto-generate readers and writers for root elements.
 - Use wsdl2h -b to auto-generate bi-directional operations (duplex ops).
 - Struct/class members serialized as XML attributes are annotated with a '@'.
 - Struct/class members that have a special role are annotated with a '$'.

WARNING:

   DO NOT INCLUDE THIS ANNOTATED FILE DIRECTLY IN YOUR PROJECT SOURCE CODE.
   USE THE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT'S SOURCE CODE:
   THE soapStub.h FILE CONTAINS THIS CONTENT WITHOUT ANNOTATIONS.

LICENSE:

@verbatim
--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.

This software is released under one of the following two licenses:
GPL or Genivia's license for commercial use.
--------------------------------------------------------------------------------
GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org

This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial-use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
@endverbatim

*/


//gsoapopt cw

/******************************************************************************\
 *                                                                            *
 * Definitions                                                                *
 *   http://www.chinatelecom.com.cn/wsdl/besttone/sms/send/v2_1/service       *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

ns1 = "http://www.chinatelecom.com.cn/wsdl/besttone/sms/send/v2_1/service"

*/

#define SOAP_NAMESPACE_OF_ns1	"http://www.chinatelecom.com.cn/wsdl/besttone/sms/send/v2_1/service"
//gsoap ns1   schema namespace:	http://www.chinatelecom.com.cn/wsdl/besttone/sms/send/v2_1/service
//gsoap ns1   schema elementForm:	qualified
//gsoap ns1   schema attributeForm:	unqualified

/******************************************************************************\
 *                                                                            *
 * Built-in Schema Types and Top-Level Elements and Attributes                *
 *                                                                            *
\******************************************************************************/



/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://www.chinatelecom.com.cn/wsdl/besttone/sms/send/v2_1/service       *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://www.chinatelecom.com.cn/wsdl/besttone/sms/send/v2_1/service       *
 *                                                                            *
\******************************************************************************/


/// "http://www.chinatelecom.com.cn/wsdl/besttone/sms/send/v2_1/service":ArrayOf_xsd_string is a complexType.
struct ns1__ArrayOf_USCORExsd_USCOREstring
{
/// Size of array of char** is 0..unbounded
   $int                                  __sizeitem                     0;
/// Array char** of length 0..unbounded
    char**                               item                           0;
};

/// "http://www.chinatelecom.com.cn/wsdl/besttone/sms/send/v2_1/service":SendSmsRequest is a complexType.
struct ns1__SendSmsRequest
{
/// Element message of type xs:string.
    char*                                message                       ;	///< Nillable pointer.
/// Element receiverAddress of type "http://www.chinatelecom.com.cn/wsdl/besttone/sms/send/v2_1/service":ArrayOf_xsd_string.
    struct ns1__ArrayOf_USCORExsd_USCOREstring*  receiverAddress               ;	///< Nillable pointer.
/// Element senderAddress of type xs:string.
    char*                                senderAddress                 ;	///< Nillable pointer.
};

/// "http://www.chinatelecom.com.cn/wsdl/besttone/sms/send/v2_1/service":SendSmsResponse is a complexType.
struct ns1__SendSmsResponse
{
/// Element requestIdentifier of type xs:string.
    char*                                requestIdentifier             ;	///< Nillable pointer.
};

/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://www.chinatelecom.com.cn/wsdl/besttone/sms/send/v2_1/service       *
 *                                                                            *
\******************************************************************************/


/// Top-level root element "http://www.chinatelecom.com.cn/wsdl/besttone/sms/send/v2_1/service":in0 of type "http://www.chinatelecom.com.cn/wsdl/besttone/sms/send/v2_1/service":SendSmsRequest.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://www.chinatelecom.com.cn/wsdl/besttone/sms/send/v2_1/service":sendSmsReturn of type "http://www.chinatelecom.com.cn/wsdl/besttone/sms/send/v2_1/service":SendSmsResponse.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://www.chinatelecom.com.cn/wsdl/besttone/sms/send/v2_1/service       *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap ns1  service name:	SendSmsServiceSoapBinding 
//gsoap ns1  service type:	SendSmsService 
//gsoap ns1  service port:	http://localhost:8080/services/SendSmsService 
//gsoap ns1  service namespace:	http://www.chinatelecom.com.cn/wsdl/besttone/sms/send/v2_1/service 
//gsoap ns1  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage Service Definitions

@section Service_bindings Service Bindings

  - @ref SendSmsServiceSoapBinding

@section Service_more More Information

  - @ref page_notes "Usage Notes"

  - @ref page_XMLDataBinding "XML Data Binding"

  - @ref SOAP_ENV__Header "SOAP Header Content" (when applicable)

  - @ref SOAP_ENV__Detail "SOAP Fault Detail Content" (when applicable)


*/

/**

@page SendSmsServiceSoapBinding Binding "SendSmsServiceSoapBinding"

@section SendSmsServiceSoapBinding_operations Operations of Binding  "SendSmsServiceSoapBinding"

  - @ref __ns1__sendSms

@section SendSmsServiceSoapBinding_ports Endpoints of Binding  "SendSmsServiceSoapBinding"

  - http://localhost:8080/services/SendSmsService

Note: use wsdl2h option -Nname to change the service binding prefix name


*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   SendSmsServiceSoapBinding                                                *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__sendSms                                                           *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__sendSms" of service binding "SendSmsServiceSoapBinding"

/**

Operation details:

  - SOAP document/literal style messaging

  - Addressing input action: ""

  - Addressing output action: "Response"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__sendSms(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    struct ns1__SendSmsRequest*         ns1__in0,
    // output parameters:
    struct ns1__SendSmsResponse*        ns1__sendSmsReturn
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__sendSms(
    struct soap *soap,
    // input parameters:
    struct ns1__SendSmsRequest*         ns1__in0,
    // output parameters:
    struct ns1__SendSmsResponse*        ns1__sendSmsReturn
  );
@endcode

*/

//gsoap ns1  service method-protocol:	sendSms SOAP
//gsoap ns1  service method-style:	sendSms document
//gsoap ns1  service method-encoding:	sendSms literal
//gsoap ns1  service method-action:	sendSms ""
//gsoap ns1  service method-output-action:	sendSms Response
int __ns1__sendSms(
    struct ns1__SendSmsRequest*         ns1__in0,	///< Input parameter
    struct ns1__SendSmsResponse*        ns1__sendSmsReturn	///< Output parameter
);

/**

@page SendSmsServiceSoapBinding Binding "SendSmsServiceSoapBinding"

@section SendSmsServiceSoapBinding_policy_enablers Policy Enablers of Binding  "SendSmsServiceSoapBinding"

Based on policies, this service imports

  - WS-Policy reminders and enablers:
    - WS-Addressing 1.0 (2005/08, accepts 2004/08):
	@code
	#import "wsa5.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsaapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	// See the user guide gsoap/doc/wsa/html/index.html
	@endcode
    - WS-Addressing (2004/08):
	@code
	#import "wsa.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsaapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	// See the user guide gsoap/doc/wsa/html/index.html
	@endcode
    - WS-ReliableMessaging 1.0:
	@code
	#import "wsrm5.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsrmapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	soap_register_plugin(soap, soap_wsrm); // register the wsrm plugin in your code
	// See the user guide gsoap/doc/wsrm/html/index.html
	@endcode
    - WS-ReliableMessaging 1.1:
	@code
	#import "wsrm.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsrmapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	soap_register_plugin(soap, soap_wsrm); // register the wsrm plugin in your code
	// See the user guide gsoap/doc/wsrm/html/index.html
	@endcode
    - WS-Security (SOAP Message Security) 1.0 (accepts 1.1):
	@code
	#import "wsse.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsseapi.h"
	soap_register_plugin(soap, soap_wsse); // register the wsse plugin in your code
	// See the user guide gsoap/doc/wsse/html/index.html
	@endcode
    - WS-Security (SOAP Message Security) 1.1 (accepts 1.0):
	@code
	#import "wsse11.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsseapi.h"
	soap_register_plugin(soap, soap_wsse); // register the wsse plugin in your code
	// See the user guide gsoap/doc/wsse/html/index.html
	@endcode
    - HTTP Digest Authentication:
	@code
	#include "plugin/httpda.h"
	soap_register_plugin(soap, soap_http_da); // register the HTTP DA plugin in your code
	// See the user guide gsoap/doc/httpda/html/index.html
	@endcode
*/


/******************************************************************************\
 *                                                                            *
 * XML Data Binding                                                           *
 *                                                                            *
\******************************************************************************/


/**

@page page_XMLDataBinding XML Data Binding

SOAP/XML services use data bindings contractually bound by WSDL and auto-
generated by wsdl2h and soapcpp2 (see Service Bindings). Plain data bindings
are adopted from XML schemas as part of the WSDL types section or when running
wsdl2h on a set of schemas to produce non-SOAP-based XML data bindings.

The following readers and writers are C/C++ data type (de)serializers auto-
generated by wsdl2h and soapcpp2. Run soapcpp2 on this file to generate the
(de)serialization code, which is stored in soapC.c[pp]. Include "soapH.h" in
your code to import these data type and function declarations. Only use the
soapcpp2-generated files in your project build. Do not include the wsdl2h-
generated .h file in your code.

Data can be read in XML and deserialized from:
  - a file descriptor, using soap->recvfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->is = ...
  - a buffer, using the soap->frecv() callback

Data can be serialized in XML and written to:
  - a file descriptor, using soap->sendfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->os = ...
  - a buffer, using the soap->fsend() callback

The following options are available for (de)serialization control:
  - soap->encodingStyle = NULL; to remove SOAP 1.1/1.2 encodingStyle
  - soap_mode(soap, SOAP_XML_TREE); XML without id-ref (no cycles!)
  - soap_mode(soap, SOAP_XML_GRAPH); XML with id-ref (including cycles)
  - soap_set_namespaces(soap, struct Namespace *nsmap); to set xmlns bindings


@section ns1 Top-level root elements of schema "http://www.chinatelecom.com.cn/wsdl/besttone/sms/send/v2_1/service"

  - <ns1:in0> (use wsdl2h option -g to auto-generate)

  - <ns1:sendSmsReturn> (use wsdl2h option -g to auto-generate)

*/

/* End of SendSmsService.h */
