/* soapStub.h
   Generated by gSOAP 2.8.15 from SendSmsService.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapStub_H
#define soapStub_H
#define SOAP_NAMESPACE_OF_ns1	"http://www.chinatelecom.com.cn/wsdl/besttone/sms/send/v2_1/service"
#include "stdsoap2.h"
#if GSOAP_VERSION != 20815
# error "GSOAP VERSION MISMATCH IN GENERATED CODE: PLEASE REINSTALL PACKAGE"
#endif

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_ns1__ArrayOf_USCORExsd_USCOREstring
#define SOAP_TYPE_ns1__ArrayOf_USCORExsd_USCOREstring (7)
/* ns1:ArrayOf_xsd_string */
struct ns1__ArrayOf_USCORExsd_USCOREstring
{
	int __sizeitem;	/* sequence of elements <item> */
	char **item;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__SendSmsRequest
#define SOAP_TYPE_ns1__SendSmsRequest (9)
/* ns1:SendSmsRequest */
struct ns1__SendSmsRequest
{
	char *message;	/* optional element of type xsd:string */
	struct ns1__ArrayOf_USCORExsd_USCOREstring *receiverAddress;	/* optional element of type ns1:ArrayOf_xsd_string */
	char *senderAddress;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__SendSmsResponse
#define SOAP_TYPE_ns1__SendSmsResponse (11)
/* ns1:SendSmsResponse */
struct ns1__SendSmsResponse
{
	char *requestIdentifier;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE___ns1__sendSms
#define SOAP_TYPE___ns1__sendSms (15)
/* Operation wrapper: */
struct __ns1__sendSms
{
	struct ns1__SendSmsRequest *ns1__in0;	/* optional element of type ns1:SendSmsRequest */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (16)
/* SOAP Header: */
enum xsd__boolean { xsd__boolean__false_ = 0, xsd__boolean__true_ = 1 };
struct ns4__RequestSOAPHeader
{
	char *cpID;	/* required element of type xsd:string */
	char *cpPassword;	/* required element of type xsd:string */
	char *timeStamp;	/* required element of type xsd:string */
	char *productID;	/* required element of type xsd:string */
	char *linkID;	/* optional element of type xsd:string */
	enum xsd__boolean *multicastMessaging;	/* optional element of type xsd:boolean */
};
struct SOAP_ENV__Header
{
	struct ns4__RequestSOAPHeader *ns4__RequestSOAPHeader;
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (17)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (19)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	char *__any;
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (22)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (23)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 __ns1__sendSms(struct soap*, struct ns1__SendSmsRequest *ns1__in0, struct ns1__SendSmsResponse *ns1__sendSmsReturn);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__sendSms(struct soap*);

/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__sendSms(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns1__SendSmsRequest *ns1__in0, struct ns1__SendSmsResponse *ns1__sendSmsReturn);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
