/* IsmpSpEngine.h
   Generated by wsdl2h 1.2.17 from IsmpSpEngine.wsdl and typemap.dat
   2010-07-30 03:04:08 GMT

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS
   USE THE soapcpp2-GENERATED SOURCE CODE FILES FOR YOUR PROJECT BUILDS

   gSOAP XML Web services tools.
   Copyright (C) 2001-2010 Robert van Engelen, Genivia Inc. All Rights Reserved.
   Part of this software is released under one of the following licenses:
   GPL or Genivia's license for commercial use.
*/

/** @page page_notes Usage Notes

NOTE:

 - Run soapcpp2 on IsmpSpEngine.h to generate the SOAP/XML processing logic.
   Use soapcpp2 option -I to specify paths for #import
   To build with STL, 'stlvector.h' is imported from 'import' dir in package.
   Use soapcpp2 option -i to generate improved proxy and server classes.
 - Use wsdl2h options -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Use Doxygen (www.doxygen.org) on this file to generate documentation.
 - Use wsdl2h options -nname and -Nname to globally rename the prefix 'ns'.
 - Use wsdl2h option -d to enable DOM support for xsd:anyType.
 - Use wsdl2h option -g to auto-generate readers and writers for root elements.
 - Struct/class members serialized as XML attributes are annotated with a '@'.
 - Struct/class members that have a special role are annotated with a '$'.

WARNING:

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS.
   USE THE SOURCE CODE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT BUILDS:
   THE soapStub.h FILE CONTAINS THIS CONTENT WITHOUT ANNOTATIONS.

LICENSE:

@verbatim
--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.

This software is released under one of the following two licenses:
1) GPL or 2) Genivia's license for commercial use.
--------------------------------------------------------------------------------
1) GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org
--------------------------------------------------------------------------------
2) A commercial-use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
@endverbatim

*/


//gsoapopt cw

/******************************************************************************\
 *                                                                            *
 * Definitions                                                                *
 *   http://sp.ismp.chinatelecom.com                                          *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

ns1 = "http://sp.ismp.chinatelecom.com"
ns2 = "http://req.sp.ismp.chinatelecom.com"
ns3 = "http://rsp.sp.ismp.chinatelecom.com"

*/

#define SOAP_NAMESPACE_OF_ns2	"http://req.sp.ismp.chinatelecom.com"
//gsoap ns2   schema namespace:	http://req.sp.ismp.chinatelecom.com
//gsoap ns2   schema elementForm:	qualified
//gsoap ns2   schema attributeForm:	unqualified

#define SOAP_NAMESPACE_OF_ns1	"http://sp.ismp.chinatelecom.com"
//gsoap ns1   schema namespace:	http://sp.ismp.chinatelecom.com
//gsoap ns1   schema elementForm:	qualified
//gsoap ns1   schema attributeForm:	unqualified

#define SOAP_NAMESPACE_OF_ns3	"http://rsp.sp.ismp.chinatelecom.com"
//gsoap ns3   schema namespace:	http://rsp.sp.ismp.chinatelecom.com
//gsoap ns3   schema elementForm:	qualified
//gsoap ns3   schema attributeForm:	unqualified

/******************************************************************************\
 *                                                                            *
 * Built-in Schema Types and Top-Level Elements and Attributes                *
 *                                                                            *
\******************************************************************************/



/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://req.sp.ismp.chinatelecom.com                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://sp.ismp.chinatelecom.com                                          *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://rsp.sp.ismp.chinatelecom.com                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://req.sp.ismp.chinatelecom.com                                      *
 *                                                                            *
\******************************************************************************/


/// "http://req.sp.ismp.chinatelecom.com":OrderRelationUpdateNotifyReq is a complexType.
struct ns2__OrderRelationUpdateNotifyReq
{
/// Element OPType of type xs:int.
    int                                  OPType                         1;	///< Required element.
/// Element packageID of type xs:string.
    char*                                packageID                      0;	///< Nullable pointer.
/// Element oldPackageID of type xs:string.
    char*                                oldPackageID                   0;	///< Nullable pointer.
/// Element productID of type xs:string.
    char*                                productID                      0;	///< Nullable pointer.
/// Element oldProductID of type xs:string.
    char*                                oldProductID                   0;	///< Nullable pointer.
/// Element streamingNo of type xs:string.
    char*                                streamingNo                   ;	///< Nullable pointer.
/// Element userID of type xs:string.
    char*                                userID                        ;	///< Nullable pointer.
/// Element userIDType of type xs:int.
    int                                  userIDType                     1;	///< Required element.
/// Size of array of char** is 0..unbounded
   $int                                  __sizeVerUserID                0;
/// Array char** of length 0..unbounded
    char**                               VerUserID                      0;	///< Nullable pointer.
};

/// "http://req.sp.ismp.chinatelecom.com":SPWithdrawSubscriptionReq is a complexType.
struct ns2__SPWithdrawSubscriptionReq
{
/// Element userIDType of type xs:int.
    int                                  userIDType                     1;	///< Required element.
/// Element userID of type xs:string.
    char*                                userID                        ;	///< Nullable pointer.
/// Element IDType of type xs:int.
    int                                  IDType                         1;	///< Required element.
/// Element ID of type xs:string.
    char*                                ID                            ;	///< Nullable pointer.
/// Element streamingNo of type xs:string.
    char*                                streamingNo                   ;	///< Nullable pointer.
/// Element SPID of type xs:string.
    char*                                SPID                          ;	///< Nullable pointer.
/// Element SPAdmin of type xs:string.
    char*                                SPAdmin                       ;	///< Nullable pointer.
/// Element SPAdminPwd of type xs:string.
    char*                                SPAdminPwd                    ;	///< Nullable pointer.
};

/// "http://req.sp.ismp.chinatelecom.com":ServiceConsumeNotifyReq is a complexType.
struct ns2__ServiceConsumeNotifyReq
{
/// Element featureStr of type xs:string.
    char*                                featureStr                    ;	///< Nullable pointer.
/// Element linkID of type xs:string.
    char*                                linkID                        ;	///< Nullable pointer.
/// Element productID of type xs:string.
    char*                                productID                     ;	///< Nullable pointer.
/// Element streamingNo of type xs:string.
    char*                                streamingNo                   ;	///< Nullable pointer.
/// Element userID of type xs:string.
    char*                                userID                        ;	///< Nullable pointer.
/// Element userIDType of type xs:int.
    int                                  userIDType                     1;	///< Required element.
};

/// "http://req.sp.ismp.chinatelecom.com":NotifyManagementInfoReq is a complexType.
struct ns2__NotifyManagementInfoReq
{
/// Element ID of type xs:string.
    char*                                ID                            ;	///< Nullable pointer.
/// Element IDType of type xs:int.
    int                                  IDType                         1;	///< Required element.
/// Element status of type xs:int.
    int                                  status                         1;	///< Required element.
/// Element streamingNo of type xs:string.
    char*                                streamingNo                   ;	///< Nullable pointer.
};

/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://sp.ismp.chinatelecom.com                                          *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://rsp.sp.ismp.chinatelecom.com                                      *
 *                                                                            *
\******************************************************************************/


/// "http://rsp.sp.ismp.chinatelecom.com":Response is a complexType.
struct ns3__Response
{
/// Element resultCode of type xs:int.
    int                                  resultCode                     1;	///< Required element.
/// Element streamingNo of type xs:string.
    char*                                streamingNo                   ;	///< Nullable pointer.
};

/// "http://rsp.sp.ismp.chinatelecom.com":NotifyManagementInfoRsp is a complexType.
struct ns3__NotifyManagementInfoRsp
{
/// Element resultCode of type xs:int.
    int                                  resultCode                     1;	///< Required element.
/// Element streamingNo of type xs:string.
    char*                                streamingNo                   ;	///< Nullable pointer.
};

/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://req.sp.ismp.chinatelecom.com                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://req.sp.ismp.chinatelecom.com                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://sp.ismp.chinatelecom.com                                          *
 *                                                                            *
\******************************************************************************/


/// Top-level root element "http://sp.ismp.chinatelecom.com":orderRelationUpdateNotifyReq of type "http://req.sp.ismp.chinatelecom.com":OrderRelationUpdateNotifyReq.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://sp.ismp.chinatelecom.com":orderRelationUpdateNotifyReturn of type "http://rsp.sp.ismp.chinatelecom.com":Response.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://sp.ismp.chinatelecom.com":spWithdrawSubscriptionReqPara of type "http://req.sp.ismp.chinatelecom.com":SPWithdrawSubscriptionReq.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://sp.ismp.chinatelecom.com":spWithdrawSubscriptionReturn of type "http://rsp.sp.ismp.chinatelecom.com":Response.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://sp.ismp.chinatelecom.com":serviceConsumeNotifyReqPara of type "http://req.sp.ismp.chinatelecom.com":ServiceConsumeNotifyReq.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://sp.ismp.chinatelecom.com":serviceConsumeNotifyReturn of type "http://rsp.sp.ismp.chinatelecom.com":Response.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://sp.ismp.chinatelecom.com":notifyManagementInfoReq of type "http://req.sp.ismp.chinatelecom.com":NotifyManagementInfoReq.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://sp.ismp.chinatelecom.com":notifyManagementInfoReturn of type "http://rsp.sp.ismp.chinatelecom.com":NotifyManagementInfoRsp.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://sp.ismp.chinatelecom.com                                          *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://rsp.sp.ismp.chinatelecom.com                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://rsp.sp.ismp.chinatelecom.com                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap ns1  service name:	IsmpSpEngineSoapBinding 
//gsoap ns1  service type:	IsmpSpEngine 
//gsoap ns1  service port:	http://localhost:8383/WsdlProject/services/IsmpSpEngine 
//gsoap ns1  service namespace:	http://sp.ismp.chinatelecom.com 
//gsoap ns1  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage Service Definitions

@section Service_bindings Service Bindings

  - @ref IsmpSpEngineSoapBinding

@section Service_more More Information

  - @ref page_notes "Usage Notes"

  - @ref page_XMLDataBinding "XML Data Binding"

  - @ref SOAP_ENV__Header "SOAP Header Content" (when applicable)

  - @ref SOAP_ENV__Detail "SOAP Fault Detail Content" (when applicable)


*/

/**

@page IsmpSpEngineSoapBinding Binding "IsmpSpEngineSoapBinding"

@section IsmpSpEngineSoapBinding_operations Operations of Binding  "IsmpSpEngineSoapBinding"

  - @ref __ns1__orderRelationUpdateNotify

  - @ref __ns1__spWithdrawSubscription

  - @ref __ns1__serviceConsumeNotify

  - @ref __ns1__notifyManagementInfo

@section IsmpSpEngineSoapBinding_ports Endpoints of Binding  "IsmpSpEngineSoapBinding"

  - http://localhost:8383/WsdlProject/services/IsmpSpEngine

Note: use wsdl2h option -N to change the service binding prefix name

*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   IsmpSpEngineSoapBinding                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__orderRelationUpdateNotify                                         *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__orderRelationUpdateNotify" of service binding "IsmpSpEngineSoapBinding"

/**

Operation details:


  - SOAP document/literal style messaging

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__orderRelationUpdateNotify(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    struct ns2__OrderRelationUpdateNotifyReq* ns1__orderRelationUpdateNotifyReq,
    // response parameters:
    struct ns3__Response*               ns1__orderRelationUpdateNotifyReturn
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__orderRelationUpdateNotify(
    struct soap *soap,
    // request parameters:
    struct ns2__OrderRelationUpdateNotifyReq* ns1__orderRelationUpdateNotifyReq,
    // response parameters:
    struct ns3__Response*               ns1__orderRelationUpdateNotifyReturn
  );
@endcode

*/

//gsoap ns1  service method-style:	orderRelationUpdateNotify document
//gsoap ns1  service method-encoding:	orderRelationUpdateNotify literal
int __ns1__orderRelationUpdateNotify(
    struct ns2__OrderRelationUpdateNotifyReq* ns1__orderRelationUpdateNotifyReq,	///< Request parameter
    struct ns3__Response*               ns1__orderRelationUpdateNotifyReturn	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__spWithdrawSubscription                                            *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__spWithdrawSubscription" of service binding "IsmpSpEngineSoapBinding"

/**

Operation details:


  - SOAP document/literal style messaging

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__spWithdrawSubscription(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    struct ns2__SPWithdrawSubscriptionReq* ns1__spWithdrawSubscriptionReqPara,
    // response parameters:
    struct ns3__Response*               ns1__spWithdrawSubscriptionReturn
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__spWithdrawSubscription(
    struct soap *soap,
    // request parameters:
    struct ns2__SPWithdrawSubscriptionReq* ns1__spWithdrawSubscriptionReqPara,
    // response parameters:
    struct ns3__Response*               ns1__spWithdrawSubscriptionReturn
  );
@endcode

*/

//gsoap ns1  service method-style:	spWithdrawSubscription document
//gsoap ns1  service method-encoding:	spWithdrawSubscription literal
int __ns1__spWithdrawSubscription(
    struct ns2__SPWithdrawSubscriptionReq* ns1__spWithdrawSubscriptionReqPara,	///< Request parameter
    struct ns3__Response*               ns1__spWithdrawSubscriptionReturn	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__serviceConsumeNotify                                              *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__serviceConsumeNotify" of service binding "IsmpSpEngineSoapBinding"

/**

Operation details:


  - SOAP document/literal style messaging

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__serviceConsumeNotify(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    struct ns2__ServiceConsumeNotifyReq* ns1__serviceConsumeNotifyReqPara,
    // response parameters:
    struct ns3__Response*               ns1__serviceConsumeNotifyReturn
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__serviceConsumeNotify(
    struct soap *soap,
    // request parameters:
    struct ns2__ServiceConsumeNotifyReq* ns1__serviceConsumeNotifyReqPara,
    // response parameters:
    struct ns3__Response*               ns1__serviceConsumeNotifyReturn
  );
@endcode

*/

//gsoap ns1  service method-style:	serviceConsumeNotify document
//gsoap ns1  service method-encoding:	serviceConsumeNotify literal
int __ns1__serviceConsumeNotify(
    struct ns2__ServiceConsumeNotifyReq* ns1__serviceConsumeNotifyReqPara,	///< Request parameter
    struct ns3__Response*               ns1__serviceConsumeNotifyReturn	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__notifyManagementInfo                                              *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__notifyManagementInfo" of service binding "IsmpSpEngineSoapBinding"

/**

Operation details:


  - SOAP document/literal style messaging

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__notifyManagementInfo(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    struct ns2__NotifyManagementInfoReq* ns1__notifyManagementInfoReq,
    // response parameters:
    struct ns3__NotifyManagementInfoRsp* ns1__notifyManagementInfoReturn
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__notifyManagementInfo(
    struct soap *soap,
    // request parameters:
    struct ns2__NotifyManagementInfoReq* ns1__notifyManagementInfoReq,
    // response parameters:
    struct ns3__NotifyManagementInfoRsp* ns1__notifyManagementInfoReturn
  );
@endcode

*/

//gsoap ns1  service method-style:	notifyManagementInfo document
//gsoap ns1  service method-encoding:	notifyManagementInfo literal
int __ns1__notifyManagementInfo(
    struct ns2__NotifyManagementInfoReq* ns1__notifyManagementInfoReq,	///< Request parameter
    struct ns3__NotifyManagementInfoRsp* ns1__notifyManagementInfoReturn	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * XML Data Binding                                                           *
 *                                                                            *
\******************************************************************************/


/**

@page page_XMLDataBinding XML Data Binding

SOAP/XML services use data bindings contractually bound by WSDL and auto-
generated by wsdl2h and soapcpp2 (see Service Bindings). Plain data bindings
are adopted from XML schemas as part of the WSDL types section or when running
wsdl2h on a set of schemas to produce non-SOAP-based XML data bindings.

The following readers and writers are C/C++ data type (de)serializers auto-
generated by wsdl2h and soapcpp2. Run soapcpp2 on this file to generate the
(de)serialization code, which is stored in soapC.c[pp]. Include "soapH.h" in
your code to import these data type and function declarations. Only use the
soapcpp2-generated files in your project build. Do not include the wsdl2h-
generated .h file in your code.

XML content can be retrieved from:
  - a file descriptor, using soap->recvfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->is = ...
  - a buffer, using the soap->frecv() callback

XML content can be stored to:
  - a file descriptor, using soap->sendfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->os = ...
  - a buffer, using the soap->fsend() callback


@section ns2 Top-level root elements of schema "http://req.sp.ismp.chinatelecom.com"

@section ns1 Top-level root elements of schema "http://sp.ismp.chinatelecom.com"

  - <ns1:orderRelationUpdateNotifyReq> (use wsdl2h option -g to auto-generate)

  - <ns1:orderRelationUpdateNotifyReturn> (use wsdl2h option -g to auto-generate)

  - <ns1:spWithdrawSubscriptionReqPara> (use wsdl2h option -g to auto-generate)

  - <ns1:spWithdrawSubscriptionReturn> (use wsdl2h option -g to auto-generate)

  - <ns1:serviceConsumeNotifyReqPara> (use wsdl2h option -g to auto-generate)

  - <ns1:serviceConsumeNotifyReturn> (use wsdl2h option -g to auto-generate)

  - <ns1:notifyManagementInfoReq> (use wsdl2h option -g to auto-generate)

  - <ns1:notifyManagementInfoReturn> (use wsdl2h option -g to auto-generate)

@section ns3 Top-level root elements of schema "http://rsp.sp.ismp.chinatelecom.com"

*/

/* End of IsmpSpEngine.h */
