/* soapClient.c
   Generated by gSOAP 2.8.15 from IsmpSpEngine.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.8.15 2013-08-09 08:41:13 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__orderRelationUpdateNotify(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns2__OrderRelationUpdateNotifyReq *ns1__orderRelationUpdateNotifyReq, struct ns3__Response *ns1__orderRelationUpdateNotifyReturn)
{	struct __ns1__orderRelationUpdateNotify soap_tmp___ns1__orderRelationUpdateNotify;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8383/WsdlProject/services/IsmpSpEngine";
	if (soap_action == NULL)
		soap_action = "http://sp.ismp.chinatelecom.com/IsmpSpEngine/orderRelationUpdateNotifyRequest";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__orderRelationUpdateNotify.ns1__orderRelationUpdateNotifyReq = ns1__orderRelationUpdateNotifyReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__orderRelationUpdateNotify(soap, &soap_tmp___ns1__orderRelationUpdateNotify);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__orderRelationUpdateNotify(soap, &soap_tmp___ns1__orderRelationUpdateNotify, "-ns1:orderRelationUpdateNotify", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__orderRelationUpdateNotify(soap, &soap_tmp___ns1__orderRelationUpdateNotify, "-ns1:orderRelationUpdateNotify", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__orderRelationUpdateNotifyReturn)
		return soap_closesock(soap);
	soap_default_ns3__Response(soap, ns1__orderRelationUpdateNotifyReturn);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns3__Response(soap, ns1__orderRelationUpdateNotifyReturn, "ns1:orderRelationUpdateNotifyReturn", "ns3:Response");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__spWithdrawSubscription(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns2__SPWithdrawSubscriptionReq *ns1__spWithdrawSubscriptionReqPara, struct ns3__Response *ns1__spWithdrawSubscriptionReturn)
{	struct __ns1__spWithdrawSubscription soap_tmp___ns1__spWithdrawSubscription;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8383/WsdlProject/services/IsmpSpEngine";
	if (soap_action == NULL)
		soap_action = "http://sp.ismp.chinatelecom.com/IsmpSpEngine/spWithdrawSubscriptionRequest";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__spWithdrawSubscription.ns1__spWithdrawSubscriptionReqPara = ns1__spWithdrawSubscriptionReqPara;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__spWithdrawSubscription(soap, &soap_tmp___ns1__spWithdrawSubscription);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__spWithdrawSubscription(soap, &soap_tmp___ns1__spWithdrawSubscription, "-ns1:spWithdrawSubscription", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__spWithdrawSubscription(soap, &soap_tmp___ns1__spWithdrawSubscription, "-ns1:spWithdrawSubscription", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__spWithdrawSubscriptionReturn)
		return soap_closesock(soap);
	soap_default_ns3__Response(soap, ns1__spWithdrawSubscriptionReturn);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns3__Response(soap, ns1__spWithdrawSubscriptionReturn, "ns1:spWithdrawSubscriptionReturn", "ns3:Response");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__serviceConsumeNotify(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns2__ServiceConsumeNotifyReq *ns1__serviceConsumeNotifyReqPara, struct ns3__Response *ns1__serviceConsumeNotifyReturn)
{	struct __ns1__serviceConsumeNotify soap_tmp___ns1__serviceConsumeNotify;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8383/WsdlProject/services/IsmpSpEngine";
	if (soap_action == NULL)
		soap_action = "http://sp.ismp.chinatelecom.com/IsmpSpEngine/serviceConsumeNotifyRequest";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__serviceConsumeNotify.ns1__serviceConsumeNotifyReqPara = ns1__serviceConsumeNotifyReqPara;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__serviceConsumeNotify(soap, &soap_tmp___ns1__serviceConsumeNotify);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__serviceConsumeNotify(soap, &soap_tmp___ns1__serviceConsumeNotify, "-ns1:serviceConsumeNotify", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__serviceConsumeNotify(soap, &soap_tmp___ns1__serviceConsumeNotify, "-ns1:serviceConsumeNotify", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__serviceConsumeNotifyReturn)
		return soap_closesock(soap);
	soap_default_ns3__Response(soap, ns1__serviceConsumeNotifyReturn);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns3__Response(soap, ns1__serviceConsumeNotifyReturn, "ns1:serviceConsumeNotifyReturn", "ns3:Response");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__notifyManagementInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns2__NotifyManagementInfoReq *ns1__notifyManagementInfoReq, struct ns3__NotifyManagementInfoRsp *ns1__notifyManagementInfoReturn)
{	struct __ns1__notifyManagementInfo soap_tmp___ns1__notifyManagementInfo;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8383/WsdlProject/services/IsmpSpEngine";
	if (soap_action == NULL)
		soap_action = "http://sp.ismp.chinatelecom.com/IsmpSpEngine/notifyManagementInfoRequest";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__notifyManagementInfo.ns1__notifyManagementInfoReq = ns1__notifyManagementInfoReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__notifyManagementInfo(soap, &soap_tmp___ns1__notifyManagementInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__notifyManagementInfo(soap, &soap_tmp___ns1__notifyManagementInfo, "-ns1:notifyManagementInfo", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__notifyManagementInfo(soap, &soap_tmp___ns1__notifyManagementInfo, "-ns1:notifyManagementInfo", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__notifyManagementInfoReturn)
		return soap_closesock(soap);
	soap_default_ns3__NotifyManagementInfoRsp(soap, ns1__notifyManagementInfoReturn);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_ns3__NotifyManagementInfoRsp(soap, ns1__notifyManagementInfoReturn, "ns1:notifyManagementInfoReturn", "ns3:NotifyManagementInfoRsp");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
